// Code generated by alef — DO NOT EDIT.
// alef:hash:6fb8fa8f6c39830b74ba145a3c4fc391bfc1a05a6e0e4ff08ea89780879f002a
package xberg

// RequireNativeSetup_1_1_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_1_0 = "1.1.0"
