// Code generated by alef — DO NOT EDIT.
// alef:hash:10f377f90cf5cca787de0bdcff45ddac9bb0b94ba3968f362215738e74196d4e
package xberg

// RequireNativeSetup_1_3_6 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_3_6 = "1.3.6"
