// Code generated by alef — DO NOT EDIT.
// alef:hash:e71491988b67f5f12a90c57540e33e829962053ef3a8e5ee486980773754db4d
package xberg

// RequireNativeSetup_1_3_5 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_3_5 = "1.3.5"
