// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f589b9a5253cfa7a50351d72043bc8ac4ace914316b84944758789f4aaf919c8
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
	},
});
