// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:67e068ab56495acb71bbb36b97e5d1caa1756b12b05aed54a64236363f403c3f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
	},
});
