# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:390784cfccd3c353d6356163b728bb6eda6cabcb28e7328eb26efcdaf3d42f77
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      _result = Xberg.clear_embedding_backends()
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Xberg.list_embedding_backends()
      refute is_nil(result)
    end
  end
end
