# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e61ed3123271963173b8fa1388b67a09663cf09855bebe6136416d8c2686876
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      _result = Xberg.clear_embedding_backends()
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Xberg.list_embedding_backends()
      refute is_nil(result)
    end
  end
end
