# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:67e068ab56495acb71bbb36b97e5d1caa1756b12b05aed54a64236363f403c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      result = Xberg.clear_embedding_backends()
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Xberg.list_embedding_backends()
    end
  end
end
