# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3e6212ec0608696344a615edd2a7fc4d3c6d3649e15f6985a744bf022769f04f
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: ocr_backend_management
defmodule E2e.OcrBackendManagementTest do
  use ExUnit.Case, async: false

  describe "ocr_backends_clear" do
    test "ocr_backends_clear" do
      _result = Xberg.clear_ocr_backends()
    end
  end

  describe "ocr_backends_list" do
    test "ocr_backends_list" do
      result = Xberg.list_ocr_backends()
      refute is_nil(result)
    end
  end

  describe "ocr_backends_unregister" do
    test "ocr_backends_unregister" do
      _result = Xberg.unregister_ocr_backend("nonexistent-backend-xyz")
    end
  end
end
