# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ebdd0665eb20af70c39fe65b08e56c758b7dd76ae9790169203b21caa5ab6967
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: ocr_backend_management
defmodule E2e.OcrBackendManagementTest do
  use ExUnit.Case, async: false

  describe "ocr_backends_clear" do
    test "ocr_backends_clear" do
      _result = Xberg.clear_ocr_backends()
    end
  end

  describe "ocr_backends_list" do
    test "ocr_backends_list" do
      result = Xberg.list_ocr_backends()
      refute is_nil(result)
    end
  end

  describe "ocr_backends_unregister" do
    test "ocr_backends_unregister" do
      _result = Xberg.unregister_ocr_backend("nonexistent-backend-xyz")
    end
  end
end
