# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: post_processor_management
defmodule E2e.PostProcessorManagementTest do
  use ExUnit.Case, async: false

  describe "post_processors_clear" do
    test "post_processors_clear" do
      result = Xberg.clear_post_processors()
    end
  end

  describe "post_processors_list" do
    test "post_processors_list" do
      result = Xberg.list_post_processors()
    end
  end
end
