# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f43699867f5abcd8cb7cbae8d9110f318661acc455820c92f6b8a0f5c46b3740
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: post_processor_management
defmodule E2e.PostProcessorManagementTest do
  use ExUnit.Case, async: false

  describe "post_processors_clear" do
    test "post_processors_clear" do
      _result = Xberg.clear_post_processors()
    end
  end

  describe "post_processors_list" do
    test "post_processors_list" do
      result = Xberg.list_post_processors()
      refute is_nil(result)
    end
  end
end
