# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1a6b6705b5a11f1f59dc10f64f446641db994f82831acec3bb6eeb35ffe8e72b
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: summarization
defmodule E2e.SummarizationTest do
  use ExUnit.Case, async: false

  describe "summarization_extractive_smoke" do
    test "summarization_extractive_smoke" do
      input_mock_base_url =
        System.get_env("MOCK_SERVER_SUMMARIZATION_EXTRACTIVE_SMOKE") ||
          "#{System.get_env("MOCK_SERVER_URL")}/fixtures/summarization_extractive_smoke"

      input_value = %Xberg.ExtractInput{
        kind: "uri",
        uri: String.replace("$mock_url/text/book_war_and_peace_1p.txt", "$mock_url", input_mock_base_url)
      }

      {:ok, result} = Xberg.extract(input: input_value, config: "{\"summarization\":{\"max_tokens\":80,\"strategy\":\"extractive\"}}")
      assert Enum.at(result.results, 0).mime_type == "text/plain"
      assert Enum.at(result.results, 0).summary.text not in [nil, "", [], %{}]
      assert Xberg.SummaryStrategy.wire_value(Enum.at(result.results, 0).summary.strategy) == "extractive"
    end
  end
end
