# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: tokenizer_backend_management
defmodule E2e.TokenizerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "tokenizer_backends_clear" do
    test "tokenizer_backends_clear" do
      result = Xberg.clear_tokenizer_backends()
    end
  end

  describe "tokenizer_backends_list" do
    test "tokenizer_backends_list" do
      result = Xberg.list_tokenizer_backends()
    end
  end
end
