# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3466aed4094cf2e745bd8f8b41b74fd044c5934627faff7d77046ea21edec89b
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: tokenizer_backend_management
defmodule E2e.TokenizerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "tokenizer_backends_clear" do
    test "tokenizer_backends_clear" do
      _result = Xberg.clear_tokenizer_backends()
    end
  end

  describe "tokenizer_backends_list" do
    test "tokenizer_backends_list" do
      result = Xberg.list_tokenizer_backends()
      refute is_nil(result)
    end
  end
end
