# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:34508c1de111d97cca33cf79918faef9e8d21d4d0e64bb1b430e5c93733bcfcd
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: validator_management
defmodule E2e.ValidatorManagementTest do
  use ExUnit.Case, async: false

  describe "validators_clear" do
    test "validators_clear" do
      _result = Xberg.clear_validators()
    end
  end

  describe "validators_list" do
    test "validators_list" do
      result = Xberg.list_validators()
      refute is_nil(result)
    end
  end
end
