// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: validator_management.</summary>
    public class ValidatorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ValidatorsClear()
        {
            // Clear all validators and verify list is empty
            XbergConverter.ClearValidators();
        }

        [Fact]
        public void Test_ValidatorsList()
        {
            // List all registered validators
            var result = XbergConverter.ListValidators();

        }


    }
}
