// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dde714e19715d1b7e4b892905ae746387d9407f6885f450c6448406ae1b3ad5d
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;

/** E2e tests for category: embedding_backend_management. */
public class EmbeddingBackendManagementTest {

    @BeforeAll
    static void initEnv() {
        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }
    }


    @Test
    void testEmbeddingBackendsClear() throws Exception {
        // Clear all embedding backends and verify list is empty
        assertDoesNotThrow(() -> Xberg.clearEmbeddingBackends());


    }


    @Test
    void testEmbeddingBackendsList() throws Exception {
        // List all registered embedding backends
        var result = Xberg.listEmbeddingBackends();
        assertNotNull(result, "expected non-null response");


    }

}
