// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32c5b61855711fb75400de16083febbfbf8f9c65ab84a1e4fc5397ce200fbb40
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;

/** E2e tests for category: post_processor_management. */
public class PostProcessorManagementTest {

    @BeforeAll
    static void initEnv() {
        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }
    }


    @Test
    void testPostProcessorsClear() throws Exception {
        // Clear all post-processors and verify list is empty
        assertDoesNotThrow(() -> Xberg.clearPostProcessors());


    }


    @Test
    void testPostProcessorsList() throws Exception {
        // List all registered post-processors
        var result = Xberg.listPostProcessors();
        assertNotNull(result, "expected non-null response");


    }

}
