// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;
/** E2e tests for category: registry. */
public class RegistryTest {
    @BeforeAll
    static void initEnv() {        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }    }

    @Test
    void testListEmbeddingBackends() throws Exception {
        // List embedding backends
        var result = Xberg.listEmbeddingBackends();


    }


    @Test
    void testListOcrBackends() throws Exception {
        // List OCR backends
        var result = Xberg.listOcrBackends();


    }


    @Test
    void testListPostProcessors() throws Exception {
        // List post-processors
        var result = Xberg.listPostProcessors();


    }


    @Test
    void testListRenderers() throws Exception {
        // List renderers
        var result = Xberg.listRenderers();


    }


    @Test
    void testListValidators() throws Exception {
        // List validators
        var result = Xberg.listValidators();


    }

}
