// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5d6ba2e554209e9c2907e8170e25d7f9326b41b87b8b1659eb21e0e918319f77
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;
/** E2e tests for category: reranker_backend_management. */
public class RerankerBackendManagementTest {
    @BeforeAll
    static void initEnv() {        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }    }

    @Test
    void testClearRerankerBackends() throws Exception {
        // Clear all reranker backends and verify list is empty
        Xberg.clearRerankerBackends();


    }


    @Test
    void testListRerankerBackends() throws Exception {
        // List all registered reranker backends
        var result = Xberg.listRerankerBackends();


    }

}
