// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:95536b6a0482a53e5d75be79306fec0ee1ddbcde9ef56889b2432faa59fd4b03
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: embedding_backend_management

use xberg::{clear_embedding_backends, list_embedding_backends};

#[test]
fn test_embedding_backends_clear() {
    // Clear all embedding backends and verify list is empty
    let _ = clear_embedding_backends().expect("call failed");
}

#[test]
fn test_embedding_backends_list() {
    // List all registered embedding backends
    let _ = list_embedding_backends().expect("call failed");
}
