// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: embedding_backend_management

use xberg::{clear_embedding_backends, list_embedding_backends};

#[test]
fn test_embedding_backends_clear() {
    // Clear all embedding backends and verify list is empty
    let _ = clear_embedding_backends();
}

#[test]
fn test_embedding_backends_list() {
    // List all registered embedding backends
    let _ = list_embedding_backends();
}
