// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: reranker_backend_management

use xberg::{clear_reranker_backends, list_reranker_backends};

#[test]
fn test_clear_reranker_backends() {
    // Clear all reranker backends and verify list is empty
    let _ = clear_reranker_backends();
}

#[test]
fn test_list_reranker_backends() {
    // List all registered reranker backends
    let _ = list_reranker_backends();
}
