// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: tokenizer_backend_management

use xberg::{clear_tokenizer_backends, list_tokenizer_backends};

#[test]
fn test_tokenizer_backends_clear() {
    // Clear all tokenizer backends and verify list is empty
    let _ = clear_tokenizer_backends();
}

#[test]
fn test_tokenizer_backends_list() {
    // List all registered tokenizer backends
    let _ = list_tokenizer_backends();
}
