// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cad429bfce84e08a879cd1c6cc8ee32b825b5cccc1bfd81b6a5857ef037a368c
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: tokenizer_backend_management

use xberg::{clear_tokenizer_backends, list_tokenizer_backends};

#[test]
fn test_tokenizer_backends_clear() {
    // Clear all tokenizer backends and verify list is empty
    let _ = clear_tokenizer_backends();
}

#[test]
fn test_tokenizer_backends_list() {
    // List all registered tokenizer backends
    let _ = list_tokenizer_backends();
}
