// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:02a92572b7446d88d53dafabdfcd29b5005e7097f78aa9e7b187d3a6e2485ade
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: tokenizer_backend_management

use xberg::{clear_tokenizer_backends, list_tokenizer_backends};

#[test]
fn test_tokenizer_backends_clear() {
    // Clear all tokenizer backends and verify list is empty
    let _ = clear_tokenizer_backends();
}

#[test]
fn test_tokenizer_backends_list() {
    // List all registered tokenizer backends
    let _ = list_tokenizer_backends();
}
