// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: validator_management

use xberg::{clear_validators, list_validators};

#[test]
fn test_validators_clear() {
    // Clear all validators and verify list is empty
    let _ = clear_validators();
}

#[test]
fn test_validators_list() {
    // List all registered validators
    let _ = list_validators();
}
