// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: validator_management

use xberg::{clear_validators, list_validators};

#[test]
fn test_validators_clear() {
    // Clear all validators and verify list is empty
    let _ = clear_validators();
}

#[test]
fn test_validators_list() {
    // List all registered validators
    let _ = list_validators();
}
