# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ArchiveEntry do
  @moduledoc """
  A single file extracted from an archive.

  When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
  enabled, each processable file produces its own full `ExtractedDocument`.
  """

  @typedoc "A single file extracted from an archive."
  @type t :: %__MODULE__{
  path: String.t() | nil,
  mime_type: String.t() | nil,
  result: Xberg.ExtractedDocument.t()
  }

  defstruct path: nil,
  mime_type: nil,
  result: nil
end
