# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b778ee0a52f3786a89465e2611c6122bff89a13f4e209c14fb43786df8d3bb14
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Attributes do
  @moduledoc """
  Element attributes in Djot.

  Represents the attributes attached to elements using {.class #id key="value"} syntax.
  """

  @typedoc "Element attributes in Djot."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          classes: [String.t()],
          key_values: [Xberg.KeyValueAttribute.t()]
        }

  defstruct id: nil,
            classes: [],
            key_values: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
