# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.BrowserMode do
  @moduledoc "When to use the headless browser fallback."

  @typedoc "When to use the headless browser fallback."
  @type t :: :auto | :always | :never | :stealth

  @auto :auto
  @always :always
  @never :never
  @stealth :stealth

  @doc "Automatically detect when JS rendering is needed and fall back to browser."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Always use the browser for every request."
  @spec always() :: t()
  def always, do: @always
  @doc "Never use the browser fallback."
  @spec never() :: t()
  def never, do: @never
  @doc "Always use the browser with all stealth surfaces enabled."
  @spec stealth() :: t()
  def stealth, do: @stealth
end
