# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62f28ac660c2f0f66b5fadbec012320eb9e1d06d6d1251505720bab8bf6e954e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
  llm: Xberg.LlmConfig.t(),
  prompt: String.t() | nil,
  min_image_area: non_neg_integer()
  }

  defstruct llm: nil,
  prompt: nil,
  min_image_area: 0
end
