# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f3a1d1aab8cc8bdf743233cecfcbeecb702981600943936b4a4de78ebd8c13bf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
          llm: Xberg.LlmConfig.t(),
          prompt: String.t() | nil,
          min_image_area: non_neg_integer()
        }

  defstruct llm: nil,
            prompt: nil,
            min_image_area: 0
end
