# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8223de234c615e991d75e921a27af61748efbddecee00cfdf1973b67f30fb429
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
          llm: Xberg.LlmConfig.t(),
          prompt: String.t() | nil,
          min_image_area: non_neg_integer()
        }

  defstruct llm: nil,
            prompt: nil,
            min_image_area: nil
end
