# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CellChange do
  @moduledoc """
  A single changed cell within a table.

  Defined here (rather than only in `crate::diff`) so `RevisionDelta` can
  reference it unconditionally, without requiring the `diff` Cargo feature.
  `crate::diff` re-exports this type verbatim.
  """

  @typedoc "A single changed cell within a table."
  @type t :: %__MODULE__{
  row: non_neg_integer(),
  col: non_neg_integer(),
  from: String.t() | nil,
  to: String.t() | nil
  }

  defstruct row: 0,
  col: 0,
  from: nil,
  to: nil
end
