# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkInfo do
  @moduledoc "Information about a single chunk."

  @typedoc "Information about a single chunk."
  @type t :: %__MODULE__{
  index: non_neg_integer(),
  pages: Xberg.PageRange.t(),
  estimated_time_ms: non_neg_integer()
  }

  defstruct index: 0,
  pages: nil,
  estimated_time_ms: 0
end
