# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c257c1321506b1f3029e4c1b7754280155b10cfedcc0e622fa1200617b818a00
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkInfo do
  @moduledoc "Information about a single chunk."

  @typedoc "Information about a single chunk."
  @type t :: %__MODULE__{
  index: non_neg_integer(),
  pages: Xberg.PageRange.t(),
  estimated_time_ms: non_neg_integer()
  }

  defstruct index: 0,
  pages: nil,
  estimated_time_ms: 0
end
