# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkInfo do
  @moduledoc "Information about a single chunk."

  @typedoc "Information about a single chunk."
  @type t :: %__MODULE__{
  index: non_neg_integer(),
  pages: Xberg.PageRange.t(),
  estimated_time_ms: non_neg_integer()
  }

  defstruct index: 0,
  pages: nil,
  estimated_time_ms: 0
end
