# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de4849a812588cb0917cd1e50dc285b82acd659ee5299f00f46ad7457300ea6c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Chunk do
  @moduledoc """
  A text chunk with optional embedding and metadata.

  Chunks are created when chunking is enabled in `ExtractionConfig`. Each chunk
  contains the text content, optional embedding vector (if embedding generation
  is configured), and metadata about its position in the document.
  """

  @typedoc "A text chunk with optional embedding and metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          chunk_type: String.t() | nil,
          embedding: [float()] | nil,
          sparse_embedding: Xberg.SparseEmbedding.t() | nil,
          late_interaction: Xberg.MultiVectorEmbedding.t() | nil,
          metadata: Xberg.ChunkMetadata.t()
        }

  defstruct content: nil,
            chunk_type: :unknown,
            embedding: nil,
            sparse_embedding: nil,
            late_interaction: nil,
            metadata: nil
end
