# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c257c1321506b1f3029e4c1b7754280155b10cfedcc0e622fa1200617b818a00
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CitationMetadata do
  @moduledoc "Citation file metadata (RIS, PubMed, EndNote)."

  @typedoc "Citation file metadata (RIS, PubMed, EndNote)."
  @type t :: %__MODULE__{
  citation_count: non_neg_integer(),
  format: String.t() | nil,
  authors: [String.t()],
  year_range: Xberg.YearRange.t() | nil,
  dois: [String.t()],
  keywords: [String.t()]
  }

  defstruct citation_count: 0,
  format: nil,
  authors: [],
  year_range: nil,
  dois: [],
  keywords: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
