# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de4849a812588cb0917cd1e50dc285b82acd659ee5299f00f46ad7457300ea6c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Citation do
  @moduledoc """
  A structured citation from a citation block.

  Parsed from entries like:
  `[^srcN]: source, locator, excerpt: "text"`
  """

  @typedoc "A structured citation from a citation block."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          source: String.t() | nil,
          locator: String.t() | nil,
          excerpt: String.t() | nil
        }

  defstruct label: nil,
            source: nil,
            locator: nil,
            excerpt: nil
end
