# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:033326cf4df4a1288ef59535f1dd633331270c5fd9097bc013d6e7df3dcb25cf
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ClassificationLabel do
  @moduledoc "A single label + confidence pair."

  @typedoc "A single label + confidence pair."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          confidence: float() | nil
        }

  defstruct label: nil,
            confidence: nil
end
