# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CodeDataAttribute do
  @moduledoc """
  An XML-style attribute attached to an [`Element`](CodeDataNodeKind::Element) node.

  Populated only for `CodeDataNodeKind::Element`; always empty for `KeyValue` and
  `Sequence` nodes.
  """

  @typedoc "An XML-style attribute attached to an [`Element`](CodeDataNodeKind::Element) node."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  value: String.t() | nil,
  byte_start: non_neg_integer(),
  byte_end: non_neg_integer()
  }

  defstruct name: nil,
  value: nil,
  byte_start: 0,
  byte_end: 0
end
