# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:37f6353770d91b81319e4672c3334342638c437b1218fa8c318bdd54ceaacb28
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CodeDataNode do
  @moduledoc """
  A node in the hierarchical data tree produced by data-format extraction.

  Purpose-built payload owned by xberg — mirrors
  `tree_sitter_language_pack::DataNode` but flattens its `Span` down to plain byte
  offsets, so binding generators never need to resolve an external crate's types
  across FFI/language boundaries.
  """

  @typedoc "A node in the hierarchical data tree produced by data-format extraction."
  @type t :: %__MODULE__{
          kind: Xberg.CodeDataNodeKind.t(),
          key: String.t() | nil,
          value: String.t() | nil,
          attributes: [Xberg.CodeDataAttribute.t()],
          children: [Xberg.CodeDataNode.t()],
          byte_start: non_neg_integer(),
          byte_end: non_neg_integer()
        }

  defstruct kind: :key_value,
            key: nil,
            value: nil,
            attributes: [],
            children: [],
            byte_start: 0,
            byte_end: 0
end
