# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eb9444a6af53db2b2c518ca98963e44d48f458a42b381f5ea4a1fab7f4d6a2fc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ContentLayer do
  @moduledoc """
  Content layer classification for document nodes.

  Replaces separate body/furniture arrays with per-node granularity.
  """

  @typedoc "Content layer classification for document nodes."
  @type t :: :body | :header | :footer | :footnote

  @body :body
  @header :header
  @footer :footer
  @footnote :footnote

  @doc "Main document body content."
  @spec body() :: t()
  def body, do: @body
  @doc "Page/section header (running header)."
  @spec header() :: t()
  def header, do: @header
  @doc "Page/section footer (running footer)."
  @spec footer() :: t()
  def footer, do: @footer
  @doc "Footnote content."
  @spec footnote() :: t()
  def footnote, do: @footnote

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:body), do: "body"
  def wire_value(:header), do: "header"
  def wire_value(:footer), do: "footer"
  def wire_value(:footnote), do: "footnote"
end
