# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  role: String.t() | nil
  }

  defstruct name: nil,
  role: nil
end
