# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  field_type: String.t() | nil
  }

  defstruct name: nil,
  field_type: nil
end
