# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:640498c28465cd7c3da00bb214bc3827aa86515cadfae0af07488506f37314c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  field_type: String.t() | nil
  }

  defstruct name: nil,
  field_type: nil
end
