# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65ff75883e7143559ab20922fe2f49df89fa9d0a5b21205b15a512ee81fa8e59
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  @typedoc "dBASE (DBF) file metadata."
  @type t :: %__MODULE__{
          record_count: non_neg_integer(),
          field_count: non_neg_integer(),
          fields: [Xberg.DbfFieldInfo.t()]
        }

  defstruct record_count: 0,
            field_count: 0,
            fields: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
