# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62f28ac660c2f0f66b5fadbec012320eb9e1d06d6d1251505720bab8bf6e954e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
  mime_type: String.t() | nil,
  filename: String.t() | nil
  }

  defstruct mime_type: nil,
  filename: nil
end
