# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
  mime_type: String.t() | nil,
  filename: String.t() | nil
  }

  defstruct mime_type: nil,
  filename: nil
end
