# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
  mime_type: String.t() | nil,
  filename: String.t() | nil
  }

  defstruct mime_type: nil,
  filename: nil
end
