# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DiffHunk do
  @moduledoc "A single contiguous hunk in a unified diff."

  @typedoc "A single contiguous hunk in a unified diff."
  @type t :: %__MODULE__{
  from_line: non_neg_integer(),
  from_count: non_neg_integer(),
  to_line: non_neg_integer(),
  to_count: non_neg_integer(),
  lines: [String.t() | nil]
  }

  defstruct from_line: 0,
  from_count: 0,
  to_line: 0,
  to_count: 0,
  lines: []
end
