# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b9bd394616c715783e40e84522ef471d629e26720706e4c5b1e1d4984b1be0e7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil
end
