# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
  src: String.t() | nil,
  alt: String.t() | nil,
  title: String.t() | nil
  }

  defstruct src: nil,
  alt: nil,
  title: nil
end
