# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62f28ac660c2f0f66b5fadbec012320eb9e1d06d6d1251505720bab8bf6e954e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  text: String.t() | nil,
  title: String.t() | nil
  }

  defstruct url: nil,
  text: nil,
  title: nil
end
