# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f053f0a746316a767a52e17321486da68b2bb30cc4afe63cd0865e67adedea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  strategy: String.t() | nil,
  token_count: non_neg_integer() | nil
  }

  defstruct text: nil,
  strategy: :extractive,
  token_count: nil
end
