# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0ed238a5461cf5524ba1e3f20cf0dcb8d5158d7e55665f7a1482edde7a474ea
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentBoundary do
  @moduledoc "Detected document boundary within a PDF."

  @typedoc "Detected document boundary within a PDF."
  @type t :: %__MODULE__{
          start_page: non_neg_integer(),
          end_page: non_neg_integer(),
          confidence: float(),
          reason: Xberg.BoundaryReason.t()
        }

  defstruct start_page: 0,
            end_page: 0,
            confidence: 0.0,
            reason: :start
end
