# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3437f3f25de23449b643e9fa4d9c6498ebc166f3b58ebc78a2d876badf537d6f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  @typedoc "A resolved relationship between two nodes in the document tree."
  @type t :: %__MODULE__{
          source: non_neg_integer(),
          target: non_neg_integer(),
          kind: String.t() | nil
        }

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
