# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentBoundary do
  @moduledoc "Detected document boundary within a PDF."

  @typedoc "Detected document boundary within a PDF."
  @type t :: %__MODULE__{
  start_page: non_neg_integer(),
  end_page: non_neg_integer(),
  confidence: float(),
  reason: String.t() | nil
  }

  defstruct start_page: 0,
  end_page: 0,
  confidence: 0.0,
  reason: :start
end
