# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  strategy: String.t() | nil,
  token_count: non_neg_integer() | nil
  }

  defstruct text: nil,
  strategy: :extractive,
  token_count: nil
end
