# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de4849a812588cb0917cd1e50dc285b82acd659ee5299f00f46ad7457300ea6c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          strategy: String.t() | nil,
          token_count: non_neg_integer() | nil
        }

  defstruct text: nil,
            strategy: :extractive,
            token_count: nil
end
