# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4cf1af7b8038dd5f64e7fb6dc71d396258e27bb9c1daf960a009324bdfe483f2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Element do
  @moduledoc """
  Semantic element extracted from document.

  Represents a logical unit of content with semantic classification,
  unique identifier, and metadata for tracking origin and position.
  """

  @typedoc "Semantic element extracted from document."
  @type t :: %__MODULE__{
          element_id: String.t() | nil,
          element_type: Xberg.ElementType.t(),
          text: String.t() | nil,
          metadata: Xberg.ElementMetadata.t()
        }

  defstruct element_id: nil,
            element_type: :title,
            text: nil,
            metadata: nil
end
