# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmailAttachment do
  @moduledoc """
  Email attachment representation.

  Contains metadata and optionally the content of an email attachment.
  """

  @typedoc "Email attachment representation."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  filename: String.t() | nil,
  mime_type: String.t() | nil,
  size: non_neg_integer() | nil,
  is_image: boolean(),
  data: binary() | nil
  }

  defstruct name: nil,
  filename: nil,
  mime_type: nil,
  size: nil,
  is_image: false,
  data: nil
end
