# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  @typedoc "Configuration for email extraction."
  @type t :: %__MODULE__{
  msg_fallback_codepage: non_neg_integer() | nil
  }

  defstruct msg_fallback_codepage: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
