# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c257c1321506b1f3029e4c1b7754280155b10cfedcc0e622fa1200617b818a00
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  data: binary(),
  compressed_size: non_neg_integer(),
  mime_type: String.t() | nil
  }

  defstruct name: nil,
  data: <<>>,
  compressed_size: 0,
  mime_type: nil
end
