# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  data: binary(),
  compressed_size: non_neg_integer(),
  mime_type: String.t() | nil
  }

  defstruct name: nil,
  data: <<>>,
  compressed_size: 0,
  mime_type: nil
end
