# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddingConfig do
  @moduledoc """
  Embedding configuration for text chunks.

  Configures embedding generation using ONNX models via the vendored embedding engine.
  Requires the `embeddings` feature to be enabled.
  """

  @typedoc "Embedding configuration for text chunks."
  @type t :: %__MODULE__{
  model: String.t() | nil,
  normalize: boolean(),
  batch_size: non_neg_integer(),
  show_download_progress: boolean(),
  cache_dir: String.t() | nil,
  acceleration: Xberg.AccelerationConfig.t() | nil,
  max_embed_duration_secs: non_neg_integer() | nil,
  max_sequence_length: non_neg_integer() | nil
  }

  defstruct model: :preset,
  normalize: true,
  batch_size: 32,
  show_download_progress: false,
  cache_dir: nil,
  acceleration: nil,
  max_embed_duration_secs: nil,
  max_sequence_length: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
