# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1a9d0b07e188ca0c03306f60b6529977341aedb3edbb0c74f21951a1d8636d4
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddedDiff do
  @moduledoc "Diff for a single embedded archive entry that appears in both results."

  @typedoc "Diff for a single embedded archive entry that appears in both results."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          diff: Xberg.ExtractionDiff.t()
        }

  defstruct path: nil,
            diff: nil
end
