# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Entity do
  @moduledoc "A single named entity detected in the extracted text."

  @typedoc "A single named entity detected in the extracted text."
  @type t :: %__MODULE__{
  category: String.t() | nil,
  text: String.t() | nil,
  start: non_neg_integer(),
  end: non_neg_integer(),
  confidence: float() | nil
  }

  defstruct category: :person,
  text: nil,
  start: 0,
  end: 0,
  confidence: nil
end
