# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
  sheets: [Xberg.ExcelSheet.t()],
  metadata: map(),
  revisions: [Xberg.DocumentRevision.t()] | nil
  }

  defstruct sheets: [],
  metadata: %{},
  revisions: nil
end
