# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
  sheets: [Xberg.ExcelSheet.t()],
  metadata: map(),
  revisions: [Xberg.DocumentRevision.t()] | nil
  }

  defstruct sheets: [],
  metadata: %{},
  revisions: nil
end
