# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3437f3f25de23449b643e9fa4d9c6498ebc166f3b58ebc78a2d876badf537d6f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
          sheets: [Xberg.ExcelSheet.t()],
          metadata: map(),
          revisions: [Xberg.DocumentRevision.t()] | nil
        }

  defstruct sheets: [],
            metadata: %{},
            revisions: nil
end
