# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @typedoc "How the extracted text was produced."
  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @doc "Text extracted directly from the document's native format (no OCR)."
  @spec native() :: t()
  def native, do: @native
  @doc "All text was obtained via OCR (e.g. scanned image-only PDF)."
  @spec ocr() :: t()
  def ocr, do: @ocr
  @doc "Text came from a combination of native extraction and OCR."
  @spec mixed() :: t()
  def mixed, do: @mixed
end
