# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:67e068ab56495acb71bbb36b97e5d1caa1756b12b05aed54a64236363f403c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractInputKind do
  @moduledoc "Source kind for [`ExtractInput`]."

  @typedoc "Source kind for [`ExtractInput`]."
  @type t :: :bytes | :uri

  @bytes :bytes
  @uri :uri

  @doc "Raw in-memory bytes."
  @spec bytes() :: t()
  def bytes, do: @bytes
  @doc "A filesystem path, `file://` URI, or HTTP(S) URL."
  @spec uri() :: t()
  def uri, do: @uri
end
