# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3525e8e5df1eaa2b7b166a3e13f384a75b864097129e07908a8fd177837e3245
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExtractionSummary do
  @moduledoc "Summary for a unified extraction call."

  @typedoc "Summary for a unified extraction call."
  @type t :: %__MODULE__{
          inputs: non_neg_integer(),
          results: non_neg_integer(),
          errors: non_neg_integer(),
          remote_urls: non_neg_integer(),
          pages_crawled: non_neg_integer(),
          documents_downloaded: non_neg_integer()
        }

  defstruct inputs: 0,
            results: 0,
            errors: 0,
            remote_urls: 0,
            pages_crawled: 0,
            documents_downloaded: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
