# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  @typedoc "FictionBook (FB2) metadata."
  @type t :: %__MODULE__{
  genres: [String.t()],
  sequences: [String.t()],
  annotation: String.t() | nil
  }

  defstruct genres: [],
  sequences: [],
  annotation: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
