# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteAnchor do
  @moduledoc """
  A footnote anchor reference in markdown text.

  Represents a `[^label]` use-site (not a definition).
  """

  @typedoc "A footnote anchor reference in markdown text."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  offset: non_neg_integer()
  }

  defstruct label: nil,
  offset: 0
end
