# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d934a97a175da2ff38df105c92d86aac885a521f05938eb7ca696bd6a2741a80
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FootnoteConfig do
  @moduledoc "Configuration for markdown footnote and citation parsing."

  @typedoc "Configuration for markdown footnote and citation parsing."
  @type t :: %__MODULE__{
          parse_citations: boolean()
        }

  defstruct parse_citations: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
