# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1417f9a5641f21ca1872c46cbc896358629de429d2c141ab376f97258b89f685
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [Xberg.FormattedBlock.t()]
        }

  defstruct label: nil,
            content: []
end
