# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f3a1d1aab8cc8bdf743233cecfcbeecb702981600943936b4a4de78ebd8c13bf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteDefinition do
  @moduledoc """
  A footnote definition from markdown text.

  Represents `[^label]: content` declarations (including multi-line continuations).
  """

  @typedoc "A footnote definition from markdown text."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: String.t() | nil,
          offset: non_neg_integer()
        }

  defstruct label: nil,
            content: nil,
            offset: 0
end
