# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteConfig do
  @moduledoc "Configuration for markdown footnote and citation parsing."

  @typedoc "Configuration for markdown footnote and citation parsing."
  @type t :: %__MODULE__{
  parse_citations: boolean()
  }

  defstruct parse_citations: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
