# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a0a67b43239d6175d74eb25514446464da31403a55553f7fb4cf8be007a1831
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FootnoteAnchor do
  @moduledoc """
  A footnote anchor reference in markdown text.

  Represents a `[^label]` use-site (not a definition).
  """

  @typedoc "A footnote anchor reference in markdown text."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          offset: non_neg_integer()
        }

  defstruct label: nil,
            offset: 0
end
