# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FormattedBlock do
  @moduledoc """
  Block-level element in a Djot document.

  Represents structural elements like headings, paragraphs, lists, code blocks, etc.
  """

  @typedoc "Block-level element in a Djot document."
  @type t :: %__MODULE__{
  block_type: String.t() | nil,
  level: non_neg_integer() | nil,
  inline_content: [Xberg.InlineElement.t()],
  language: String.t() | nil,
  code: String.t() | nil,
  children: [Xberg.FormattedBlock.t()]
  }

  defstruct block_type: :paragraph,
  level: nil,
  inline_content: [],
  language: nil,
  code: nil,
  children: []
end
