# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:640498c28465cd7c3da00bb214bc3827aa86515cadfae0af07488506f37314c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  @typedoc "Individual grid cell with position and span metadata."
  @type t :: %__MODULE__{
  content: String.t() | nil,
  row: non_neg_integer(),
  col: non_neg_integer(),
  row_span: non_neg_integer(),
  col_span: non_neg_integer(),
  is_header: boolean(),
  bbox: Xberg.BoundingBox.t() | nil
  }

  defstruct content: nil,
  row: 0,
  col: 0,
  row_span: 0,
  col_span: 0,
  is_header: false,
  bbox: nil
end
