# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:449b2f9d3e1502fdeb82061140f5a6f8774bf92ea434dc833fe90c3d01415f59
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  @typedoc "Individual grid cell with position and span metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          row: non_neg_integer(),
          col: non_neg_integer(),
          row_span: non_neg_integer(),
          col_span: non_neg_integer(),
          is_header: boolean(),
          bbox: Xberg.BoundingBox.t() | nil
        }

  defstruct content: nil,
            row: 0,
            col: 0,
            row_span: nil,
            col_span: nil,
            is_header: false,
            bbox: nil
end
