# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dab12721979e88fe6ea2991d25f6f6673cfc2c12325007aeb5e2df145e24d1d9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
          headings: [Xberg.HeadingLevel.t()]
        }

  defstruct headings: []
end
