# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62f28ac660c2f0f66b5fadbec012320eb9e1d06d6d1251505720bab8bf6e954e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  @typedoc "A single heading in the hierarchy."
  @type t :: %__MODULE__{
  level: non_neg_integer(),
  text: String.t() | nil
  }

  defstruct level: 0,
  text: nil
end
