# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ecd62fe5cf2cd8f8328ae99258ebd5e49253419ec89fd33fd9904d4205307faa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  @typedoc "A single heading in the hierarchy."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil
        }

  defstruct level: 0,
            text: nil
end
