# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
  headings: [Xberg.HeadingLevel.t()]
  }

  defstruct headings: []
end
