# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  @typedoc "A single heading in the hierarchy."
  @type t :: %__MODULE__{
  level: non_neg_integer(),
  text: String.t() | nil
  }

  defstruct level: 0,
  text: nil
end
