# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8cd07e7834702e46f14c04205e45c2be74ea0f38c871f7edcec75c06815543c5
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImageDimensions do
  @moduledoc "Image dimensions in pixels."

  @typedoc "Image dimensions in pixels."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct width: 0,
            height: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
