# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62f28ac660c2f0f66b5fadbec012320eb9e1d06d6d1251505720bab8bf6e954e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
  element_type: String.t() | nil,
  content: String.t() | nil,
  metadata: map() | nil
  }

  defstruct element_type: :text,
  content: nil,
  metadata: nil
end
