# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f053f0a746316a767a52e17321486da68b2bb30cc4afe63cd0865e67adedea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
  element_type: String.t() | nil,
  content: String.t() | nil,
  metadata: map() | nil
  }

  defstruct element_type: :text,
  content: nil,
  metadata: nil
end
