# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f3a1d1aab8cc8bdf743233cecfcbeecb702981600943936b4a4de78ebd8c13bf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          content: String.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            metadata: nil
end
