# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f35e48a160cf6aee769d8c68cd54d8dba7324e01d12486ac52909e9674952a2f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  @typedoc "JATS (Journal Article Tag Suite) metadata."
  @type t :: %__MODULE__{
          copyright: String.t() | nil,
          license: String.t() | nil,
          history_dates: map(),
          contributor_roles: [Xberg.ContributorRole.t()]
        }

  defstruct copyright: nil,
            license: nil,
            history_dates: %{},
            contributor_roles: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
