# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2cd591a1035bd3e57c8fef446ace6772d898cdd32a4d83fd3ca704db368ee776
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.KeyValueAttribute do
  @moduledoc "A string key-value attribute."

  @typedoc "A string key-value attribute."
  @type t :: %__MODULE__{
          key: String.t() | nil,
          value: String.t() | nil
        }

  defstruct key: nil,
            value: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
