# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0ddc4c4a06d0a27364a4ca37bd888268f8e2b38ad31975d873b8cf74363c2f9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  @typedoc "Keyword extraction configuration."
  @type t :: %__MODULE__{
          algorithm: Xberg.KeywordAlgorithm.t(),
          max_keywords: non_neg_integer(),
          min_score: float(),
          language: String.t() | nil,
          yake_params: Xberg.YakeParams.t() | nil,
          rake_params: Xberg.RakeParams.t() | nil
        }

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            language: nil,
            yake_params: nil,
            rake_params: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
