# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  score: float(),
  algorithm: String.t() | nil,
  positions: [non_neg_integer()] | nil
  }

  defstruct text: nil,
  score: 0.0,
  algorithm: :yake,
  positions: nil
end
