# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  @typedoc "Language detection configuration."
  @type t :: %__MODULE__{
  enabled: boolean(),
  min_confidence: float(),
  detect_multiple: boolean()
  }

  defstruct enabled: true,
  min_confidence: 0.8,
  detect_multiple: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
