# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  @typedoc "Language detection configuration."
  @type t :: %__MODULE__{
  enabled: boolean(),
  min_confidence: float(),
  detect_multiple: boolean()
  }

  defstruct enabled: true,
  min_confidence: 0.8,
  detect_multiple: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
