# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LateInteractionMatch do
  @moduledoc """
  A single document match returned by [`max_sim_rank`], with its position in
  the input and MaxSim score.

  Since v5.0.0.
  """

  @typedoc "A single document match returned by [`max_sim_rank`], with its position in the input and MaxSim score."
  @type t :: %__MODULE__{
  index: non_neg_integer(),
  score: float()
  }

  defstruct index: 0,
  score: 0.0
end
