# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d5ac116889962c3d512a6767032b804efd3add6554c5d5ae937c6efcb210f5bf
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LateInteractionPreset do
  @moduledoc """
  Static metadata for a bundled ColBERT preset (WASM/Android-safe, no ORT).

  Since v5.0.0.
  """

  @typedoc "Static metadata for a bundled ColBERT preset (WASM/Android-safe, no ORT)."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          model_repo: String.t() | nil,
          model_file: String.t() | nil,
          additional_files: [String.t()],
          max_length: non_neg_integer(),
          query_max_length: non_neg_integer(),
          dim: non_neg_integer(),
          description: String.t() | nil
        }

  defstruct name: nil,
            model_repo: nil,
            model_file: nil,
            additional_files: [],
            max_length: 0,
            query_max_length: 0,
            dim: 0,
            description: nil
end
