# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aeba5d7f8ab0c90810c4dda4a4d92f02ad319675167d7887546badffd79ca82c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
          class_name: Xberg.LayoutClass.t(),
          confidence: float(),
          bbox: Xberg.BBox.t()
        }

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
