# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LinkType do
  @moduledoc "Link type classification."

  @typedoc "Link type classification."
  @type t :: :anchor | :internal | :external | :email | :phone | :other

  @anchor :anchor
  @internal :internal
  @external :external
  @email :email
  @phone :phone
  @other :other

  @doc "Anchor link (#section)"
  @spec anchor() :: t()
  def anchor, do: @anchor
  @doc "Internal link (same domain)"
  @spec internal() :: t()
  def internal, do: @internal
  @doc "External link (different domain)"
  @spec external() :: t()
  def external, do: @external
  @doc "Email link (mailto:)"
  @spec email() :: t()
  def email, do: @email
  @doc "Phone link (tel:)"
  @spec phone() :: t()
  def phone, do: @phone
  @doc "Other link type"
  @spec other() :: t()
  def other, do: @other
end
