# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
  href: String.t() | nil,
  text: String.t() | nil,
  title: String.t() | nil,
  link_type: String.t() | nil,
  rel: [String.t()]
  }

  defstruct href: nil,
  text: nil,
  title: nil,
  link_type: :anchor,
  rel: []
end
