# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d7e615239864ab587624f5f434214826b1b18850b54f39166f374333f8414feb
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LlmCacheConfig do
  @moduledoc """
  Response cache configuration.

  Mirrors liter-llm's `LlmCacheConfig`. Only takes effect when liter-llm's `tower`
  feature is compiled in; otherwise the value round-trips through configuration
  but is not consulted at request time.
  """

  @typedoc "Response cache configuration."
  @type t :: %__MODULE__{
          max_entries: non_neg_integer() | nil,
          ttl_seconds: non_neg_integer() | nil,
          backend: String.t() | nil,
          backend_config: map() | nil
        }

  defstruct max_entries: nil,
            ttl_seconds: nil,
            backend: nil,
            backend_config: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
