# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.MetaSchema do
  @moduledoc "Compiled meta-schema validator over `preset.schema.json`."

  alias Xberg.Native
  defstruct [:ref]

  @typedoc "Compiled meta-schema validator over `preset.schema.json`."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Compile the given JSON text as a Draft 2020-12 meta-schema."
  def compile(meta_schema_json) do
    ref = Native.metaschema_compile(meta_schema_json)
    %__MODULE__{ref: ref}
  end

  @doc "Validate `raw` against the meta-schema and deserialize into a [`Preset`],"
  def parse_preset(obj, path, raw) do
    Native.metaschema_parse_preset(obj.ref, path, raw)
  end
end
