# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
  page_count: non_neg_integer(),
  pages: [Xberg.PageSignals.t()]
  }

  defstruct page_count: 0,
  pages: []
end
