# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
  page_count: non_neg_integer(),
  pages: [Xberg.PageSignals.t()]
  }

  defstruct page_count: 0,
  pages: []
end
