# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3ed18eb65dd91042903ee233dfdb7710409494343796a808d1ec6277da9cff11
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MultidocThresholds do
  @moduledoc """
  Thresholds for multi-document boundary detection.

  All fields are public; callers override any subset via struct-update syntax.
  """

  @typedoc "Thresholds for multi-document boundary detection."
  @type t :: %__MODULE__{
          density_shift_threshold: float(),
          bigram_overlap_min: float()
        }

  defstruct density_shift_threshold: 0.3,
            bigram_overlap_min: 0.1

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
