# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
  page_count: non_neg_integer(),
  pages: [Xberg.PageSignals.t()]
  }

  defstruct page_count: 0,
  pages: []
end
