# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:98c12a4e4f55567b7d9f5b9031594b77ac3e4200859af69e8801844db05aecc1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.NewlineStyle do
  @moduledoc """
  Line break syntax in Markdown output.

  Controls how soft line breaks (from `<br>` or line breaks in source) are rendered.
  """

  @typedoc "Line break syntax in Markdown output."
  @type t :: :spaces | :backslash

  @spaces :spaces
  @backslash :backslash

  @doc "Two trailing spaces at end of line. Default. Standard Markdown syntax."
  @spec spaces() :: t()
  def spaces, do: @spaces
  @doc "Backslash at end of line. Alternative Markdown syntax."
  @spec backslash() :: t()
  def backslash, do: @backslash

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:spaces), do: "Spaces"
  def wire_value(:backslash), do: "Backslash"
end
