# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f35fb5b62d85432b3c5f18f616e0de8cece15652070858ef3dc6f5ed7c2423f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrPoint do
  @moduledoc "A point in OCR raster pixel coordinates."

  @typedoc "A point in OCR raster pixel coordinates."
  @type t :: %__MODULE__{
          x: non_neg_integer(),
          y: non_neg_integer()
        }

  defstruct x: 0,
            y: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
