# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7561d2d9833a19f49b897f6d21b7163ec0a228e9f74b6f35c59ae812672fdeca
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  @typedoc "Bounding box for an OCR-detected table in pixel coordinates."
  @type t :: %__MODULE__{
          left: non_neg_integer(),
          top: non_neg_integer(),
          right: non_neg_integer(),
          bottom: non_neg_integer()
        }

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
