# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c257c1321506b1f3029e4c1b7754280155b10cfedcc0e622fa1200617b818a00
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @typedoc "Rotation information for an OCR element."
  @type t :: %__MODULE__{
  angle_degrees: float(),
  confidence: float() | nil
  }

  defstruct angle_degrees: 0.0,
  confidence: nil
end
