# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrTable do
  @moduledoc """
  Table detected via OCR.

  Represents a table structure recognized during OCR processing.
  """

  @typedoc "Table detected via OCR."
  @type t :: %__MODULE__{
  cells: [[String.t()]],
  markdown: String.t() | nil,
  page_number: non_neg_integer(),
  bounding_box: Xberg.OcrTableBoundingBox.t() | nil
  }

  defstruct cells: [],
  markdown: nil,
  page_number: 0,
  bounding_box: nil
end
