# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4d09771c5bda0aa5fcfea383b87dc5ac25acccd6e1396a3c540158b4d6fc089f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrBoundingGeometry do
  @moduledoc """
  Bounding geometry for an OCR element.

  Supports both axis-aligned rectangles (from Tesseract) and 4-point quadrilaterals
  (from PaddleOCR and rotated text detection).
  """

  @typedoc "Bounding geometry for an OCR element."
  @type t :: term()

  @typedoc "Axis-aligned bounding box (typical for Tesseract output)."
  @type rectangle :: %{
          type: :rectangle,
          left: non_neg_integer(),
          top: non_neg_integer(),
          width: non_neg_integer(),
          height: non_neg_integer()
        }
  @typedoc "4-point quadrilateral for rotated/skewed text (PaddleOCR)."
  @type quadrilateral :: %{type: :quadrilateral, points: String.t()}

  def rectangle(left, top, width, height), do: {:rectangle, %{left: left, top: top, width: width, height: height}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:rectangle), do: "rectangle"
  def wire_value(:quadrilateral), do: "quadrilateral"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
