# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de4849a812588cb0917cd1e50dc285b82acd659ee5299f00f46ad7457300ea6c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @typedoc "Rotation information for an OCR element."
  @type t :: %__MODULE__{
          angle_degrees: float(),
          confidence: float() | nil
        }

  defstruct angle_degrees: 0.0,
            confidence: nil
end
