# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d73dc942a0ba1f9f3e54402a2a5645093e9bc90e9f6f1fb8fc7fdb42d54589b1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  @typedoc "A single backend stage in the OCR pipeline."
  @type t :: %__MODULE__{
          backend: String.t() | nil,
          priority: non_neg_integer(),
          language: [String.t()] | nil,
          tesseract_config: Xberg.TesseractConfig.t() | nil,
          paddle_ocr_config: String.t() | nil,
          vlm_config: Xberg.LlmConfig.t() | nil,
          backend_options: String.t() | nil
        }

  defstruct backend: nil,
            priority: nil,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil,
            backend_options: nil
end
