# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  @typedoc "A single backend stage in the OCR pipeline."
  @type t :: %__MODULE__{
  backend: String.t() | nil,
  priority: non_neg_integer(),
  language: [String.t()] | nil,
  tesseract_config: Xberg.TesseractConfig.t() | nil,
  paddle_ocr_config: String.t() | nil,
  vlm_config: Xberg.LlmConfig.t() | nil,
  backend_options: String.t() | nil
  }

  defstruct backend: nil,
  priority: 0,
  language: nil,
  tesseract_config: nil,
  paddle_ocr_config: nil,
  vlm_config: nil,
  backend_options: nil
end
