# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba94fe4cec719c31f8ac484fcc2aba1d30db0f87dea8b1b6d0257417a4a260e2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageStructure do
  @moduledoc """
  Unified page structure for documents.

  Supports different page types (PDF pages, PPTX slides, Excel sheets)
  with character offset boundaries for chunk-to-page mapping.
  """

  @typedoc "Unified page structure for documents."
  @type t :: %__MODULE__{
  total_count: non_neg_integer(),
  unit_type: String.t() | nil,
  boundaries: [Xberg.PageBoundary.t()] | nil,
  pages: [Xberg.PageInfo.t()] | nil
  }

  defstruct total_count: 0,
  unit_type: :page,
  boundaries: nil,
  pages: nil
end
