# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageInfo do
  @moduledoc """
  Metadata for individual page/slide/sheet.

  Captures per-page information including dimensions, content counts,
  and visibility state (for presentations).
  """

  @typedoc "Metadata for individual page/slide/sheet."
  @type t :: %__MODULE__{
  number: non_neg_integer(),
  title: String.t() | nil,
  image_count: non_neg_integer() | nil,
  table_count: non_neg_integer() | nil,
  hidden: boolean() | nil,
  is_blank: boolean() | nil,
  has_vector_graphics: boolean()
  }

  defstruct number: 0,
  title: nil,
  image_count: nil,
  table_count: nil,
  hidden: nil,
  is_blank: nil,
  has_vector_graphics: false
end
