# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d341d44c2c385e1f867b9391de3450101dcf42434dbc6da70f34b81bbbcdb582
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageStructure do
  @moduledoc """
  Unified page structure for documents.

  Supports different page types (PDF pages, PPTX slides, Excel sheets)
  with character offset boundaries for chunk-to-page mapping.
  """

  @typedoc "Unified page structure for documents."
  @type t :: %__MODULE__{
          total_count: non_neg_integer(),
          unit_type: Xberg.PageUnitType.t(),
          boundaries: [Xberg.PageBoundary.t()] | nil,
          pages: [Xberg.PageInfo.t()] | nil
        }

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
