# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:592643cd12d8afbdccc5f5e7325dfd70cb2cacdf5a6c743b75a21b8b577e8654
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageSignals do
  @moduledoc "Per-page signals extracted from PDF content."

  @typedoc "Per-page signals extracted from PDF content."
  @type t :: %__MODULE__{
          page_number: non_neg_integer(),
          text_excerpt: String.t() | nil,
          starts_with_letterhead_like: boolean(),
          has_page_number_one_marker: boolean(),
          has_signature_block: boolean(),
          layout_text_density: float()
        }

  defstruct page_number: 0,
            text_excerpt: nil,
            starts_with_letterhead_like: false,
            has_page_number_one_marker: false,
            has_signature_block: false,
            layout_text_density: 0.0
end
