# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
  prompt_template: String.t() | nil,
  labels: [String.t()],
  multi_label: boolean(),
  llm: Xberg.LlmConfig.t()
  }

  defstruct prompt_template: nil,
  labels: [],
  multi_label: false,
  llm: nil
end
