# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5527186e4c39dc196871729c080e1e4bbb2e3a2c1a5ab8930ed166b219f201a7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageSpan do
  @moduledoc """
  A single page covered by a chunk, with an optional bounding box on that page.

  See [`ChunkMetadata::page_spans`] (#1295) for population semantics.
  """

  @typedoc "A single page covered by a chunk, with an optional bounding box on that page."
  @type t :: %__MODULE__{
          page: non_neg_integer(),
          bbox: Xberg.BoundingBox.t() | nil
        }

  defstruct page: 0,
            bbox: nil
end
