# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f053f0a746316a767a52e17321486da68b2bb30cc4afe63cd0865e67adedea8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PatternMatch do
  @moduledoc "One detected PII span in the input text."

  @typedoc "One detected PII span in the input text."
  @type t :: %__MODULE__{
  start: non_neg_integer(),
  end: non_neg_integer(),
  category: String.t() | nil,
  text: String.t() | nil
  }

  defstruct start: 0,
  end: 0,
  category: :email,
  text: nil
end
