# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:22dc08c44622f1cbbf20a70394d2030f312609ad6ed850d4655083b033a0a4f1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PatternMatch do
  @moduledoc "One detected PII span in the input text."

  @typedoc "One detected PII span in the input text."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          category: Xberg.PiiCategory.t(),
          text: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            category: :email,
            text: nil
end
