# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  @typedoc "A PDF annotation extracted from a document page."
  @type t :: %__MODULE__{
  annotation_type: String.t() | nil,
  content: String.t() | nil,
  page_number: non_neg_integer(),
  bounding_box: Xberg.BoundingBox.t() | nil
  }

  defstruct annotation_type: :text,
  content: nil,
  page_number: 0,
  bounding_box: nil
end
