# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PreprocessingOptions do
  @moduledoc "HTML preprocessing options for document cleanup before conversion."

  @typedoc "HTML preprocessing options for document cleanup before conversion."
  @type t :: %__MODULE__{
  enabled: boolean(),
  preset: String.t() | nil,
  remove_navigation: boolean(),
  remove_forms: boolean()
  }

  defstruct enabled: true,
  preset: :standard,
  remove_navigation: true,
  remove_forms: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
