# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8fe0b7190885c560673b9a263ceafa983ed4a382d1634856c22bb37937ac3f72
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PresentationHyperlink do
  @moduledoc "A hyperlink discovered in a presentation slide."

  @typedoc "A hyperlink discovered in a presentation slide."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil
        }

  defstruct url: nil,
            label: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
