# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:12d61c4479db9c0d9bcfc660e1633dd30c50a06b72fc9957c0100c2f8eedffa9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PresetSample do
  @moduledoc "Pointer to a sample input + its reference output bundled with the preset."

  @typedoc "Pointer to a sample input + its reference output bundled with the preset."
  @type t :: %__MODULE__{
          input_path: String.t() | nil,
          output_path: String.t() | nil
        }

  defstruct input_path: nil,
            output_path: nil
end
