# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ProcessingWarning do
  @moduledoc """
  A non-fatal warning from a processing pipeline stage.

  Captures errors from optional features that don't prevent extraction
  but may indicate degraded results.
  """

  @typedoc "A non-fatal warning from a processing pipeline stage."
  @type t :: %__MODULE__{
  source: String.t() | nil,
  message: String.t() | nil
  }

  defstruct source: nil,
  message: nil
end
