# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9586d4d1d60ecd76df8ce232c9a36a8de6b87e6c9c3c89637e788c3bba25de5
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PropertyChange do
  @moduledoc """
  A single run-level or style-level property change.

  Used for revisions that change formatting rather than text content. `from`
  and `to` store normalized property values when the source format exposes
  them; either side may be absent when the format only records one side of the
  change.
  """

  @typedoc "A single run-level or style-level property change."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          from: String.t() | nil,
          to: String.t() | nil
        }

  defstruct name: nil,
            from: nil,
            to: nil
end
