# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ProxyConfig do
  @moduledoc "Proxy configuration for HTTP requests."

  @typedoc "Proxy configuration for HTTP requests."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  username: String.t() | nil,
  password: String.t() | nil
  }

  defstruct url: nil,
  username: nil,
  password: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
