# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  @typedoc "Outlook PST archive metadata."
  @type t :: %__MODULE__{
  message_count: non_neg_integer()
  }

  defstruct message_count: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
