# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3437f3f25de23449b643e9fa4d9c6498ebc166f3b58ebc78a2d876badf537d6f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.QrBoundingBox do
  @moduledoc "Pixel-space bounding box of a QR code inside its source image."

  @typedoc "Pixel-space bounding box of a QR code inside its source image."
  @type t :: %__MODULE__{
          x: non_neg_integer(),
          y: non_neg_integer(),
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct x: 0,
            y: 0,
            width: 0,
            height: 0
end
