# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:67e068ab56495acb71bbb36b97e5d1caa1756b12b05aed54a64236363f403c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.QrBoundingBox do
  @moduledoc "Pixel-space bounding box of a QR code inside its source image."

  @typedoc "Pixel-space bounding box of a QR code inside its source image."
  @type t :: %__MODULE__{
  x: non_neg_integer(),
  y: non_neg_integer(),
  width: non_neg_integer(),
  height: non_neg_integer()
  }

  defstruct x: 0,
  y: 0,
  width: 0,
  height: 0
end
