# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.QrBoundingBox do
  @moduledoc "Pixel-space bounding box of a QR code inside its source image."

  @typedoc "Pixel-space bounding box of a QR code inside its source image."
  @type t :: %__MODULE__{
  x: non_neg_integer(),
  y: non_neg_integer(),
  width: non_neg_integer(),
  height: non_neg_integer()
  }

  defstruct x: 0,
  y: 0,
  width: 0,
  height: 0
end
