# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:46b0d4be124fed63f5d3d146bedc5330c2ec3fe843040959e3e66c8229c20fc2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
          payload: String.t() | nil,
          confidence: float() | nil,
          bbox: Xberg.QrBoundingBox.t() | nil
        }

  defstruct payload: nil,
            confidence: nil,
            bbox: nil
end
