# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62f28ac660c2f0f66b5fadbec012320eb9e1d06d6d1251505720bab8bf6e954e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RecognizedTable do
  @moduledoc """
  Pre-computed table markdown for a table detection region.

  Produced by the TATR-based table structure recognizer and surfaced as part of
  layout-aware OCR results.  The struct lives here (under `layout-types`, pure-Rust)
  so that consumers who do not enable `layout-detection` (ORT) can still reference
  the type in their own code.
  """

  @typedoc "Pre-computed table markdown for a table detection region."
  @type t :: %__MODULE__{
  detection_bbox: Xberg.BBox.t(),
  cells: [[String.t()]],
  markdown: String.t() | nil
  }

  defstruct detection_bbox: nil,
  cells: [],
  markdown: nil
end
