# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionFinding do
  @moduledoc "One redaction event: which span was rewritten, why, and with what."

  @typedoc "One redaction event: which span was rewritten, why, and with what."
  @type t :: %__MODULE__{
  start: non_neg_integer(),
  end: non_neg_integer(),
  category: String.t() | nil,
  strategy: String.t() | nil,
  replacement_token: String.t() | nil
  }

  defstruct start: 0,
  end: 0,
  category: :email,
  strategy: :mask,
  replacement_token: nil
end
