# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c257c1321506b1f3029e4c1b7754280155b10cfedcc0e622fa1200617b818a00
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RerankedDocument do
  @moduledoc """
  A single document returned by the reranker, with its position in the input and score.

  `index` maps back to the caller's original document list, so metadata arrays
  (e.g. IDs, paths) can be reordered without passing them through the reranker.

  Since v5.0.0.
  """

  @typedoc "A single document returned by the reranker, with its position in the input and score."
  @type t :: %__MODULE__{
  index: non_neg_integer(),
  score: float(),
  document: String.t() | nil
  }

  defstruct index: 0,
  score: 0.0,
  document: nil
end
