# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SparseEmbedding do
  @moduledoc """
  A sparse learned embedding: vocabulary term indices and their weights.

  `indices` are ascending vocabulary token ids; `values[i]` is the weight for
  `indices[i]`. The two arrays always have equal length. Only strictly-positive
  terms are retained, so the representation is genuinely sparse.

  Since v5.0.0.
  """

  @typedoc "A sparse learned embedding: vocabulary term indices and their weights."
  @type t :: %__MODULE__{
  indices: [non_neg_integer()],
  values: [float()]
  }

  defstruct indices: [],
  values: []
end
