# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:137425401174ea362794d86e5cf06ac1303471fd1249ccc85707fbbb9187f352
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.SsrfPolicy do
  @moduledoc "SSRF policy configuration."

  @typedoc "SSRF policy configuration."
  @type t :: %__MODULE__{
          deny_private: boolean(),
          allowlist: [Xberg.HostMatcher.t()],
          denylist: [Xberg.HostMatcher.t()],
          max_redirects: non_neg_integer(),
          scheme_allowlist: [String.t()]
        }

  defstruct deny_private: true,
            allowlist: [],
            denylist: [],
            max_redirects: 5,
            scheme_allowlist: ["http", "https"]

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
