# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  @typedoc "Structured data (Schema.org, microdata, RDFa) block."
  @type t :: %__MODULE__{
  data_type: String.t() | nil,
  raw_json: String.t() | nil,
  schema_type: String.t() | nil
  }

  defstruct data_type: :json_ld,
  raw_json: nil,
  schema_type: nil
end
