# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d00bd839887e8e89c5c93ef70b997247ffb6169fcbcd38c480bb0daa3f6db4b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  @typedoc "Structured data (Schema.org, microdata, RDFa) block."
  @type t :: %__MODULE__{
          data_type: Xberg.StructuredDataType.t(),
          raw_json: String.t() | nil,
          schema_type: String.t() | nil
        }

  defstruct data_type: :json_ld,
            raw_json: nil,
            schema_type: nil
end
