# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SummarizationConfig do
  @moduledoc "Configuration for the summarisation post-processor."

  @typedoc "Configuration for the summarisation post-processor."
  @type t :: %__MODULE__{
  strategy: String.t() | nil,
  max_tokens: non_neg_integer() | nil,
  llm: Xberg.LlmConfig.t() | nil
  }

  defstruct strategy: :extractive,
  max_tokens: nil,
  llm: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
