# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:640498c28465cd7c3da00bb214bc3827aa86515cadfae0af07488506f37314c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SupportedFormat do
  @moduledoc """
  A supported document format entry.

  Represents a file extension and its corresponding MIME type that Xberg can process.
  """

  @typedoc "A supported document format entry."
  @type t :: %__MODULE__{
  extension: String.t() | nil,
  mime_type: String.t() | nil
  }

  defstruct extension: nil,
  mime_type: nil
end
