# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SvgOptions do
  @moduledoc """
  SVG-specific configuration for the image-encode pipeline.

  Applies when the source image is SVG or when the output format is set to
  [`ImageOutputFormat::Svg`].  Available when the `svg` feature is active.

  Used via [`ImageExtractionConfig::svg`].
  """

  @typedoc "SVG-specific configuration for the image-encode pipeline."
  @type t :: %__MODULE__{
  sanitize: boolean(),
  render_dpi: float()
  }

  defstruct sanitize: true,
  render_dpi: 96

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
