# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7de0234404b0cc5f5173507abf913019f2e942adbedaade88683c9b6e9a2f294
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
          from_index: non_neg_integer(),
          to_index: non_neg_integer(),
          cell_changes: [Xberg.CellChange.t()]
        }

  defstruct from_index: 0,
            to_index: 0,
            cell_changes: []
end
