# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
  from_index: non_neg_integer(),
  to_index: non_neg_integer(),
  cell_changes: [Xberg.CellChange.t()]
  }

  defstruct from_index: 0,
  to_index: 0,
  cell_changes: []
end
