# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TableCell do
  @moduledoc """
  Individual table cell with content and optional styling.

  Future extension point for rich table support with cell-level metadata.
  """

  @typedoc "Individual table cell with content and optional styling."
  @type t :: %__MODULE__{
  content: String.t() | nil,
  row_span: non_neg_integer(),
  col_span: non_neg_integer(),
  is_header: boolean()
  }

  defstruct content: nil,
  row_span: 0,
  col_span: 0,
  is_header: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
