# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
  from_index: non_neg_integer(),
  to_index: non_neg_integer(),
  cell_changes: [Xberg.CellChange.t()]
  }

  defstruct from_index: 0,
  to_index: 0,
  cell_changes: []
end
