# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:41105a5db21cb9241b8e372890031fd3eaa44c52773aaf42ba0566d7f1b48d90
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TokenCounter do
  @moduledoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."

  alias Xberg.Native
  defstruct [:ref]

  @typedoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tokencounter_new()}
  end

  def default() do
    ref = Native.tokencounter_new()
    %__MODULE__{ref: ref}
  end
end
