# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ce526d8b88aaed6ed108fb6ec3eca29563b5c5be43d851273aa9c91487a1abbb
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TokenCounter do
  @moduledoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."

  alias Xberg.Native
  defstruct [:ref]

  @typedoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tokencounter_new()}
  end

  def default() do
    ref = Native.tokencounter_new()
    %__MODULE__{ref: ref}
  end
end
