# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TranslationConfig do
  @moduledoc "Configuration for the translation post-processor."

  @typedoc "Configuration for the translation post-processor."
  @type t :: %__MODULE__{
  target_lang: String.t() | nil,
  source_lang: String.t() | nil,
  preserve_markup: boolean(),
  llm: Xberg.LlmConfig.t()
  }

  defstruct target_lang: nil,
  source_lang: nil,
  preserve_markup: false,
  llm: nil
end
