# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6ed469d38c30a3b27887bc25f71e0667ec0c1f0ec6ebce5108998d248f304ff3
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.UrlExtractionMode do
  @moduledoc "URL extraction mode."

  @typedoc "URL extraction mode."
  @type t :: :auto | :document | :crawl

  @auto :auto
  @document :document
  @crawl :crawl

  @doc "Classify HTTP(S) resources after fetch."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Treat the URI as a single remote document/page."
  @spec document() :: t()
  def document, do: @document
  @doc "Crawl from the seed URI and extract discovered pages/documents."
  @spec crawl() :: t()
  def crawl, do: @crawl

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:auto), do: "auto"
  def wire_value(:document), do: "document"
  def wire_value(:crawl), do: "crawl"
end
