# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.UrlExtractionConfig do
  @moduledoc "URL ingestion and crawl configuration."

  @typedoc "URL ingestion and crawl configuration."
  @type t :: %__MODULE__{
  mode: String.t() | nil,
  crawl: Xberg.CrawlConfig.t(),
  document_url_pattern: String.t() | nil,
  max_document_urls_per_result: non_neg_integer() | nil,
  max_total_urls: non_neg_integer() | nil,
  allow_local_file_inputs: boolean(),
  allow_file_uris: boolean()
  }

  defstruct mode: :auto,
  crawl: nil,
  document_url_pattern: nil,
  max_document_urls_per_result: nil,
  max_total_urls: nil,
  allow_local_file_inputs: true,
  allow_file_uris: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
