# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:640498c28465cd7c3da00bb214bc3827aa86515cadfae0af07488506f37314c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.XmlMetadata do
  @moduledoc """
  XML metadata extracted during XML parsing.

  Provides statistics about XML document structure.
  """

  @typedoc "XML metadata extracted during XML parsing."
  @type t :: %__MODULE__{
  element_count: non_neg_integer(),
  unique_elements: [String.t()]
  }

  defstruct element_count: 0,
  unique_elements: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
