<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:96252eab3cd52937197dc701c564eb0bf50d69bb9bab5607aede31e4d2eeafb3
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: embedding_backend_management. */
final class EmbeddingBackendManagementTest extends TestCase
{


    /** Clear all embedding backends and verify list is empty */
    public function test_embedding_backends_clear(): void
    {
        $result = Xberg::clearEmbeddingBackends();

        $this->assertTrue(true, 'expected the call not to throw');


    }


    /** List all registered embedding backends */
    public function test_embedding_backends_list(): void
    {
        $result = Xberg::listEmbeddingBackends();

        $this->assertNotNull($result);


    }

}
