<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: post_processor_management. */
final class PostProcessorManagementTest extends TestCase
{

    /** Clear all post-processors and verify list is empty */
    public function test_post_processors_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearPostProcessors();


    }


    /** List all registered post-processors */
    public function test_post_processors_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listPostProcessors();


    }

}
