<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f3a1d1aab8cc8bdf743233cecfcbeecb702981600943936b4a4de78ebd8c13bf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: validator_management. */
final class ValidatorManagementTest extends TestCase
{

    /** Clear all validators and verify list is empty */
    public function test_validators_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearValidators();


    }


    /** List all registered validators */
    public function test_validators_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listValidators();


    }

}
