// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:204fe51186fcba3dce7b975cf23f9875e82c73d34a14aa4693c2246e94cbf0a1
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: code.
final class CodeTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testCodeShebangDetection() async throws {
        // Test language detection from shebang line via bytes input
        let inputMockBaseUrl = ProcessInfo.processInfo.environment["MOCK_SERVER_CODE_SHEBANG_DETECTION"] ?? (AlefE2EMockServer.baseURL + "/fixtures/code_shebang_detection")
        let inputJson = "{\"kind\":\"uri\",\"mime_type\":\"text/x-source-code\",\"uri\":\"$mock_url/code/script.sh\"}".replacingOccurrences(of: "$mock_url", with: inputMockBaseUrl)
        let result = try await Xberg.extract(inputJson, "{}")
        let _vec_results_equals_2583f5e4 = result.results()
        XCTAssertEqual(_vec_results_equals_2583f5e4[0].mimeType().toString(), "text/x-source-code")
        let _vec_results_min_length_a5fd1ce0 = result.results()
        XCTAssertGreaterThanOrEqual(_vec_results_min_length_a5fd1ce0[0].content().toString().count, 10)
        let _vec_results_contains_all_a78ad6d8 = result.results()
        XCTAssertTrue(_vec_results_contains_all_a78ad6d8[0].content().toString().contains("build"), "expected to contain: \("build")")
        XCTAssertTrue(_vec_results_contains_all_a78ad6d8[0].content().toString().contains("clean"), "expected to contain: \("clean")")
    }

}
