// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bb5d5354916eb161c739d4066fa789b70f412a30a2538c4dfd8bde8a24a424f1
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: embedding_backend_management.
final class EmbeddingBackendManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testEmbeddingBackendsClear() throws {
        // Clear all embedding backends and verify list is empty
        XCTAssertNoThrow(try Xberg.clearEmbeddingBackends())
    }

    func testEmbeddingBackendsList() throws {
        // List all registered embedding backends
        let result = try Xberg.listEmbeddingBackends()
        XCTAssertNotNil(result)
    }

}
