// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:09ff0e51c101cb89ed9ce22b9376cb52ac8deae1c280bc6358c8a9168238ea5c
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: validator_management.
final class ValidatorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testValidatorsClear() throws {
        // Clear all validators and verify list is empty
        XCTAssertNoThrow(try Xberg.clearValidators())
    }

    func testValidatorsList() throws {
        // List all registered validators
        let result = try Xberg.listValidators()
        XCTAssertNotNil(result)
    }

}
