// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The meta-schema itself failed to compile.
/// </summary>
public class BadMetaSchemaException : LoadErrorException
{
    public BadMetaSchemaException(string message) : base(message) { }

    public BadMetaSchemaException(string message, Exception innerException) : base(message, innerException) { }
}
