// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:640498c28465cd7c3da00bb214bc3827aa86515cadfae0af07488506f37314c9
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The meta-schema itself failed to compile.
/// </summary>
public class BadMetaSchemaException : LoadErrorException
{
    public BadMetaSchemaException(string message) : base(message) { }

    public BadMetaSchemaException(string message, Exception innerException) : base(message, innerException) { }
}
