// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:839797aea72233a39d43a9dfe3394c5971cc91b020fe1dd8cf0e507887fb10a5
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A cache read or write operation failed.
/// </summary>
public class CacheException : XbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
