// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A cache read or write operation failed.
/// </summary>
public class CacheException : XbergErrorException {
  public CacheException(string message) : base(message) {}

  public CacheException(string message, Exception innerException)
      : base(message, innerException) {}
}
