// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction was cancelled via a `CancellationToken`.
/// </summary>
public class CancelledException : XbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
