// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:62f28ac660c2f0f66b5fadbec012320eb9e1d06d6d1251505720bab8bf6e954e
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration value.
/// </summary>
public class ConfigErrorException : HeuristicsErrorException {
  public ConfigErrorException(string message) : base(message) {}

  public ConfigErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
