// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ba94fe4cec719c31f8ac484fcc2aba1d30db0f87dea8b1b6d0257417a4a260e2
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration value.
/// </summary>
public class ConfigErrorException : HeuristicsErrorException {
  public ConfigErrorException(string message) : base(message) {}

  public ConfigErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
