// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e1d9c8931f1309030fcece37a16d713620f9bd3f5eb2d1f2b4d5297544d8246c
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Content filter applied to each crawled page before it reaches the result.
/// </summary>
[JsonConverter(typeof(ContentFilterKindJsonConverter))]
public enum ContentFilterKind
{
    /// <summary>
    /// Keep only pages scoring at or above `bm25_threshold` for `bm25_query`.
    /// </summary>
    [JsonPropertyName("bm25")]
    Bm25,
}


/// <summary>
/// Custom JSON converter for <see cref="ContentFilterKind"/> that respects explicit variant names.
/// </summary>
internal sealed class ContentFilterKindJsonConverter : JsonConverter<ContentFilterKind>
{
    public override ContentFilterKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "bm25" => ContentFilterKind.Bm25,
            _ => throw new JsonException($"Unknown ContentFilterKind value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ContentFilterKind value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ContentFilterKind.Bm25 => "bm25",
            _ => throw new JsonException($"Unknown ContentFilterKind value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
