// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:67e068ab56495acb71bbb36b97e5d1caa1756b12b05aed54a64236363f403c3f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file validates but cannot be deserialized into `Preset`.
/// </summary>
public class DeserializeException : LoadErrorException {
  public DeserializeException(string message) : base(message) {}

  public DeserializeException(string message, Exception innerException)
      : base(message, innerException) {}
}
