// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d0533d62f53003ec69db94ad1435f96035bd0a2ae94e2058556cc1ba1090bf96
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file validates but cannot be deserialized into `Preset`.
/// </summary>
public class DeserializeException : LoadErrorException {
  public DeserializeException(string message) : base(message) {}

  public DeserializeException(string message, Exception innerException)
      : base(message, innerException) {}
}
