// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:20b927e4b71d9231394627c95f90cafcc4bdf6299189965cb46453cc0541cb24
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : XbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
