// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ba94fe4cec719c31f8ac484fcc2aba1d30db0f87dea8b1b6d0257417a4a260e2
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : XbergErrorException {
  public EmbeddingException(string message) : base(message) {}

  public EmbeddingException(string message, Exception innerException)
      : base(message, innerException) {}
}
