// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Source kind for `ExtractInput`.
/// </summary>
[JsonConverter(typeof(ExtractInputKindJsonConverter))]
public enum ExtractInputKind {
  /// <summary>
  /// Raw in-memory bytes.
  /// </summary>
  [JsonPropertyName("bytes")] Bytes,
  /// <summary>
  /// A filesystem path, `file://` URI, or HTTP(S) URL.
  /// </summary>
  [JsonPropertyName("uri")] Uri,
}

/// <summary>
/// Custom JSON converter for <see cref="ExtractInputKind"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class ExtractInputKindJsonConverter
    : JsonConverter<ExtractInputKind> {
  public override ExtractInputKind Read(ref Utf8JsonReader reader,
                                        Type typeToConvert,
                                        JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch {
      "bytes" => ExtractInputKind.Bytes, "uri" => ExtractInputKind.Uri,
      _ => throw new JsonException($"Unknown ExtractInputKind value: {value}")
    };
  }

  public override void Write(Utf8JsonWriter writer, ExtractInputKind value,
                             JsonSerializerOptions options) {
    var str = value switch {
      ExtractInputKind.Bytes => "bytes", ExtractInputKind.Uri => "uri",
      _ => throw new JsonException($"Unknown ExtractInputKind value: {value}")
    };
    writer.WriteStringValue(str);
  }
}
