// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors that can occur during heuristics analysis.
/// </summary>
public class HeuristicsErrorException : XbergException
{
    public HeuristicsErrorException(string message) : base(message) { }

    public HeuristicsErrorException(string message, Exception innerException) : base(message, innerException) { }
}
