// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors that can occur during heuristics analysis.
/// </summary>
public class HeuristicsErrorException : XbergException {
  public HeuristicsErrorException(string message) : base(message) {}

  public HeuristicsErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
