// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors that can occur during heuristics analysis.
/// </summary>
public class HeuristicsErrorException : XbergException
{
    public HeuristicsErrorException(string message) : base(message) { }

    public HeuristicsErrorException(string message, Exception innerException) : base(message, innerException) { }
}
