// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:063ff841ae87107c511dfed617b32406d31da61f27913fcb2e67e48fc458e473
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The preset's declared `id` does not match its file-system location.
/// </summary>
public class IdMismatchException : LoadErrorException
{
    public IdMismatchException(string message) : base(message) { }

    public IdMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
