// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:640498c28465cd7c3da00bb214bc3827aa86515cadfae0af07488506f37314c9
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An image manipulation operation (resize, decode, DPI conversion) failed.
/// </summary>
public class ImageProcessingException : XbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
