// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4759db1fce23a1e7708865c3181e721ab2c77f1ca17034e561842dc8525f376e
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An image manipulation operation (resize, decode, DPI conversion) failed.
/// </summary>
public class ImageProcessingException : XbergErrorException {
  public ImageProcessingException(string message) : base(message) {}

  public ImageProcessingException(string message, Exception innerException)
      : base(message, innerException) {}
}
