// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A file system or I/O operation failed. These errors always bubble up
/// unchanged.
/// </summary>
public class IoException : XbergErrorException {
  public IoException(string message) : base(message) {}

  public IoException(string message, Exception innerException)
      : base(message, innerException) {}
}
