// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:640498c28465cd7c3da00bb214bc3827aa86515cadfae0af07488506f37314c9
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A file system or I/O operation failed. These errors always bubble up unchanged.
/// </summary>
public class IoException : XbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
