// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:41105a5db21cb9241b8e372890031fd3eaa44c52773aaf42ba0566d7f1b48d90
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// A single document match returned by `max_sim_rank`, with its position in
/// the input and MaxSim score.
///
/// Since v5.0.0.
/// </summary>
public sealed record LateInteractionMatch {
  /// <summary>
  /// Position of this document in the original input slice.
  /// </summary>
  [JsonPropertyName("index")]
  public ulong Index { get; init; } = 0;

  /// <summary>
  /// MaxSim relevance score. Higher means more relevant to the query.
  /// </summary>
  [JsonPropertyName("score")]
  public float Score {
    get; init;
  } = 0.0f;

  /// <summary>
  /// Parse a <see cref="LateInteractionMatch"/> from a JSON string.
  /// </summary>
  /// <exception cref="XbergException">When the JSON cannot be
  /// deserialised.</exception>
  public static LateInteractionMatch FromJson(string json) {
    try {
      return JsonSerializer.Deserialize<LateInteractionMatch>(json,
                                                              JsonOptions) ??
             throw new XbergException(
                 $"Failed to parse LateInteractionMatch from JSON: deserializer returned null");
    } catch (XbergException) {
      throw;
    } catch (Exception e) {
      throw new XbergException(
          $"Failed to parse LateInteractionMatch from JSON: {e.Message}", e);
    }
  }

  private static readonly JsonSerializerOptions JsonOptions = new() {
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
                   new ByteArrayJsonConverter() },
  };

  /// <summary>Options for serializing config/input objects to FFI. Strips nulls
  /// (nullable C# fields default to null and would override required Rust
  /// fields with non-deserialisable nulls) but preserves explicit false/0 so
  /// caller intent is kept.</summary>
  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(
                           JsonNamingPolicy.SnakeCaseLower),
                       new ByteArrayJsonConverter() },
      };
}
