// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while loading or validating a preset file.
/// </summary>
public class LoadErrorException : XbergException {
  public LoadErrorException(string message) : base(message) {}

  public LoadErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
