// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:62f28ac660c2f0f66b5fadbec012320eb9e1d06d6d1251505720bab8bf6e954e
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An internal `Mutex` or `RwLock` was found in a poisoned state.
/// </summary>
public class LockPoisonedException : XbergErrorException {
  public LockPoisonedException(string message) : base(message) {}

  public LockPoisonedException(string message, Exception innerException)
      : base(message, innerException) {}
}
