// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:41105a5db21cb9241b8e372890031fd3eaa44c52773aaf42ba0566d7f1b48d90
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An internal `Mutex` or `RwLock` was found in a poisoned state.
/// </summary>
public class LockPoisonedException : XbergErrorException {
  public LockPoisonedException(string message) : base(message) {}

  public LockPoisonedException(string message, Exception innerException)
      : base(message, innerException) {}
}
