// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A required optional system dependency (e.g. `tesseract`) was not found.
/// </summary>
public class MissingDependencyException : XbergErrorException {
  public MissingDependencyException(string message) : base(message) {}

  public MissingDependencyException(string message, Exception innerException)
      : base(message, innerException) {}
}
