// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e34715ed0fcf22667f73dbfc0e76d0526e3d275686718021b6806261656ad7d7
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A required optional system dependency (e.g. `tesseract`) was not found.
/// </summary>
public class MissingDependencyException : XbergErrorException {
  public MissingDependencyException(string message) : base(message) {}

  public MissingDependencyException(string message, Exception innerException)
      : base(message, innerException) {}
}
