// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A required optional system dependency (e.g. `tesseract`) was not found.
/// </summary>
public class MissingDependencyException : XbergErrorException {
  public MissingDependencyException(string message) : base(message) {}

  public MissingDependencyException(string message, Exception innerException)
      : base(message, innerException) {}
}
