// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : XbergErrorException {
  public OcrException(string message) : base(message) {}

  public OcrException(string message, Exception innerException)
      : base(message, innerException) {}
}
