// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : XbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
