// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:41105a5db21cb9241b8e372890031fd3eaa44c52773aaf42ba0566d7f1b48d90
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : XbergErrorException {
  public OcrException(string message) : base(message) {}

  public OcrException(string message, Exception innerException)
      : base(message, innerException) {}
}
