// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A catch-all for uncommon errors that do not fit another variant.
/// </summary>
public class OtherException : XbergErrorException {
  public OtherException(string message) : base(message) {}

  public OtherException(string message, Exception innerException)
      : base(message, innerException) {}
}
