// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c257c1321506b1f3029e4c1b7754280155b10cfedcc0e622fa1200617b818a00
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A catch-all for uncommon errors that do not fit another variant.
/// </summary>
public class OtherException : XbergErrorException {
  public OtherException(string message) : base(message) {}

  public OtherException(string message, Exception innerException)
      : base(message, innerException) {}
}
