// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ecd62fe5cf2cd8f8328ae99258ebd5e49253419ec89fd33fd9904d4205307faa
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Document parsing failed (e.g. corrupt file, unsupported format feature).
/// </summary>
public class ParsingException : XbergErrorException {
  public ParsingException(string message) : base(message) {}

  public ParsingException(string message, Exception innerException)
      : base(message, innerException) {}
}
