// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file is not valid JSON.
/// </summary>
public class ParseException : LoadErrorException {
  public ParseException(string message) : base(message) {}

  public ParseException(string message, Exception innerException)
      : base(message, innerException) {}
}
