// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:be357a6a0f1d9696ad93ca7e932299e774377ab4348c558347ca1fd72545938a
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Document parsing failed (e.g. corrupt file, unsupported format feature).
/// </summary>
public class ParsingException : XbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
