// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ba94fe4cec719c31f8ac484fcc2aba1d30db0f87dea8b1b6d0257417a4a260e2
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// PDF analysis step failed (only when `heuristics-pdf` feature is active).
/// </summary>
public class PdfAnalysisErrorException : HeuristicsErrorException {
  public PdfAnalysisErrorException(string message) : base(message) {}

  public PdfAnalysisErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
