// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d856584eafebf608cbf7b8f5b092dbeb8868883a1c9a9f9a1abb7d3df7f0a93e
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// PDF analysis step failed (only when `heuristics-pdf` feature is active).
/// </summary>
public class PdfAnalysisErrorException : HeuristicsErrorException
{
    public PdfAnalysisErrorException(string message) : base(message) { }

    public PdfAnalysisErrorException(string message, Exception innerException) : base(message, innerException) { }
}
