// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ee05dd43b54d9d07cad49cfbfe750328c0f0a35ee079cfd1fa15c4f8982d7862
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : XbergErrorException {
  public PluginException(string message) : base(message) {}

  public PluginException(string message, Exception innerException)
      : base(message, innerException) {}
}
