// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : XbergErrorException {
  public PluginException(string message) : base(message) {}

  public PluginException(string message, Exception innerException)
      : base(message, innerException) {}
}
