// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : XbergErrorException {
  public PluginException(string message) : base(message) {}

  public PluginException(string message, Exception innerException)
      : base(message, innerException) {}
}
