// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3437f3f25de23449b643e9fa4d9c6498ebc166f3b58ebc78a2d876badf537d6f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The reranker model or reranking pipeline returned an error.
///
/// Since v5.0.0.
/// </summary>
public class RerankingException : XbergErrorException {
  public RerankingException(string message) : base(message) {}

  public RerankingException(string message, Exception innerException)
      : base(message, innerException) {}
}
