// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException {
  public ResolveErrorException(string message) : base(message) {}

  public ResolveErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
