// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fdf32ccffdd235ab1e054ee0375df54131aaae2d4a871101da93295815804d34
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException
{
    public ResolveErrorException(string message) : base(message) { }

    public ResolveErrorException(string message, Exception innerException) : base(message, innerException) { }
}
