// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:640498c28465cd7c3da00bb214bc3827aa86515cadfae0af07488506f37314c9
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException
{
    public ResolveErrorException(string message) : base(message) { }

    public ResolveErrorException(string message, Exception innerException) : base(message, innerException) { }
}
