// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2ede12a45840d0b11c46a66ee9825588c7146ee0214921d5459ee4d7b2b00929
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file parses as JSON but does not validate against the meta-schema.
/// </summary>
public class SchemaValidationException : LoadErrorException
{
    public SchemaValidationException(string message) : base(message) { }

    public SchemaValidationException(string message, Exception innerException) : base(message, innerException) { }
}
