// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9665eefd548f58fce68e384bad4eff4f3c825dc81875736a16824ff52f2993dc
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException
{
    public SchemaNotObjectException(string message) : base(message) { }

    public SchemaNotObjectException(string message, Exception innerException) : base(message, innerException) { }
}
