// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Schema-validation outcome surfaced as one of three buckets.
///
/// Fold into the combined confidence score without leaking internal validation
/// error types.
/// </summary>
[JsonConverter(typeof(SchemaComplianceJsonConverter))]
public enum SchemaCompliance {
  /// <summary>
  /// Every batch validated against the schema.
  /// </summary>
  [JsonPropertyName("all_valid")] AllValid,
  /// <summary>
  /// At least one batch validated; at least one did not.
  /// </summary>
  [JsonPropertyName("partial_valid")] PartialValid,
  /// <summary>
  /// No batch validated.
  /// </summary>
  [JsonPropertyName("all_invalid")] AllInvalid,
}

/// <summary>
/// Custom JSON converter for <see cref="SchemaCompliance"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class SchemaComplianceJsonConverter
    : JsonConverter<SchemaCompliance> {
  public override SchemaCompliance Read(ref Utf8JsonReader reader,
                                        Type typeToConvert,
                                        JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch { "all_valid" => SchemaCompliance.AllValid,
                          "partial_valid" => SchemaCompliance.PartialValid,
                          "all_invalid" => SchemaCompliance.AllInvalid,
                          _ => throw new JsonException(
                              $"Unknown SchemaCompliance value: {value}") };
  }

  public override void Write(Utf8JsonWriter writer, SchemaCompliance value,
                             JsonSerializerOptions options) {
    var str = value switch { SchemaCompliance.AllValid => "all_valid",
                             SchemaCompliance.PartialValid => "partial_valid",
                             SchemaCompliance.AllInvalid => "all_invalid",
                             _ => throw new JsonException(
                                 $"Unknown SchemaCompliance value: {value}") };
    writer.WriteStringValue(str);
  }
}
