// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b21cc0f56b08c564af9635c82e8927b2c4700e15b9eabb2e6fc215e9566545cd
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file parses as JSON but does not validate against the meta-schema.
/// </summary>
public class SchemaValidationException : LoadErrorException
{
    public SchemaValidationException(string message) : base(message) { }

    public SchemaValidationException(string message, Exception innerException) : base(message, innerException) { }
}
