// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3437f3f25de23449b643e9fa4d9c6498ebc166f3b58ebc78a2d876badf537d6f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException {
  public SchemaNotObjectException(string message) : base(message) {}

  public SchemaNotObjectException(string message, Exception innerException)
      : base(message, innerException) {}
}
