// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ecd62fe5cf2cd8f8328ae99258ebd5e49253419ec89fd33fd9904d4205307faa
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException {
  public SchemaNotObjectException(string message) : base(message) {}

  public SchemaNotObjectException(string message, Exception innerException)
      : base(message, innerException) {}
}
