// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file parses as JSON but does not validate against the meta-schema.
/// </summary>
public class SchemaValidationException : LoadErrorException {
  public SchemaValidationException(string message) : base(message) {}

  public SchemaValidationException(string message, Exception innerException)
      : base(message, innerException) {}
}
