// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:15b3b7872a233fc7d73b57c07510fb3b9954c1b09a7a82370dfdffac7fa65dcf
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : XbergErrorException {
  public SecurityException(string message) : base(message) {}

  public SecurityException(string message, Exception innerException)
      : base(message, innerException) {}
}
