// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:39e18e4871cdb4c963e745bcf5122534ee1e1a21108b899c54bd8ccef898e2ef
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : XbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
