// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : XbergErrorException {
  public SerializationException(string message) : base(message) {}

  public SerializationException(string message, Exception innerException)
      : base(message, innerException) {}
}
