// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:62f28ac660c2f0f66b5fadbec012320eb9e1d06d6d1251505720bab8bf6e954e
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction operation exceeded the configured time limit.
/// </summary>
public class TimeoutException : XbergErrorException {
  public TimeoutException(string message) : base(message) {}

  public TimeoutException(string message, Exception innerException)
      : base(message, innerException) {}
}
