// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction operation exceeded the configured time limit.
/// </summary>
public class TimeoutException : XbergErrorException {
  public TimeoutException(string message) : base(message) {}

  public TimeoutException(string message, Exception innerException)
      : base(message, innerException) {}
}
