// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c6a6e0f3cda5393c25ea51ecd248f2f8676bca2ac437c09ac1a179b26edb941a
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : XbergErrorException {
  public TranscriptionException(string message) : base(message) {}

  public TranscriptionException(string message, Exception innerException)
      : base(message, innerException) {}
}
