// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cc1a117d99396549a993cf01389d36068176aa8f1d28a95888afcc980594e258
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration or input parameters were supplied.
/// </summary>
public class ValidationException : XbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
