// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
#nullable enable

using System;

namespace Xberg;

public class XbergException : Exception {
  public int Code { get; }

  public XbergException(int code, string message) : base(message) {
    Code = code;
  }

  public XbergException(string message) : base(message) { Code = 0; }

  public XbergException(string message, Exception innerException)
      : base(message, innerException) {
    Code = 0;
  }
}
