// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0d23742a0e3fc159e99d69d72806a38b2d0957cc45c06650fedf011155a8636a
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: tokenizer_backend_management

test "tokenizer_backends_clear" {
    // Clear all tokenizer backends and verify list is empty
    allow_private_network();
    _ = try xberg.clear_tokenizer_backends();
}

test "tokenizer_backends_list" {
    // List all registered tokenizer backends
    allow_private_network();
    _ = try xberg.list_tokenizer_backends();
}
