<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Xberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    /**
     * Create a fresh counter with no previous state.
     */
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
