# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:16377d5cd4db4c27057867cddfc95bc91441b83bd3cfe8f55502bd2e567cd8bc
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: post_processor_management."""

import pytest  # noqa: F401
from xberg import clear_post_processors, list_post_processors


def test_post_processors_clear() -> None:
    """Clear all post-processors and verify list is empty."""
    clear_post_processors()


def test_post_processors_list() -> None:
    """List all registered post-processors."""
    result = list_post_processors()
    assert result is not None  # noqa: S101
