# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cba6e06777f7a81d989840473852d7f472a271c6917c3877c53833f0219a43ef
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: embedding_backend_management."""

import pytest  # noqa: F401
from xberg import clear_embedding_backends, list_embedding_backends


def test_embedding_backends_clear() -> None:
    """Clear all embedding backends and verify list is empty."""
    clear_embedding_backends()


def test_embedding_backends_list() -> None:
    """List all registered embedding backends."""
    result = list_embedding_backends()
    assert result is not None
