# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5df979a25404d127b818148520e1db384e03510ee17f75b423aacb3345d82087
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: renderer_management."""

import pytest  # noqa: F401
from xberg import clear_renderers, list_renderers


def test_renderers_clear() -> None:
    """Clear all renderers and verify list is empty."""
    clear_renderers()


def test_renderers_list() -> None:
    """List all registered renderers."""
    result = list_renderers()
    assert result is not None  # noqa: S101
