# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ecd62fe5cf2cd8f8328ae99258ebd5e49253419ec89fd33fd9904d4205307faa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "xberg/version"
require_relative "xberg/native"

# Top-level namespace for the Xberg Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "xberg/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Xberg
  # Re-export all types and functions from native extension
end

# Keep generated types under Xberg. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
