# Generated by alef. Do not edit by hand.
# alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.** { *; }
