// Generated by alef. Do not edit by hand.
// alef:hash:de861d0ec16c92017ae0c726cb50a8a67f75c75695fc229ba6f2d9b97c8b5915
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Configuration for the VLM captioning post-processor. */
data class CaptioningConfig(
    /** LLM configuration used for the VLM call. */
    val llm: LlmConfig,
    /**
     * Optional custom caption prompt. `null` uses the default `RegionKind.Caption`
     * prompt that ships with `crate.llm.region_extractor`.
     */
    val prompt: String? = null,
    /**
     * Skip images whose `width * height` is below this threshold (in pixels).
     * Default `1_000` filters out icons and decorations.
     */
    val minImageArea: Int,
)
