// Generated by alef. Do not edit by hand.
// alef:hash:53c778c706ff078c36d70a7a4ac52fc13a9c62bc8e891ad4a1e8a659dec63780
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * A single labeled definition the chunk classifier may emit.
 *
 * Unlike `PageClassificationConfig.labels` (bare label names), chunk
 * classification targets potentially large domain taxonomies where every
 * label carries its own semantic description, letting the LLM disambiguate
 * similarly named labels without relying on the label string alone.
 */
data class ChunkClassificationDefinition(
    /** Label name returned in `ChunkMetadata.classifications`. */
    val label: String,
    /**
     * Semantic description of when this label applies. Injected verbatim into
     * the classification prompt next to the label name.
     */
    val description: String,
)
