// Generated by alef. Do not edit by hand.
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Citation file metadata (RIS, PubMed, EndNote). */
data class CitationMetadata(
    /** Total number of citation records in the file. */
    val citationCount: Long = 0L,
    /** Detected citation file format (e.g. `"ris"`, `"pubmed"`, `"endnote"`). */
    val format: String? = null,
    /** Author names collected across all citation records. */
    val authors: List<String> = emptyList(),
    /** Earliest and latest publication years found in the file. */
    val yearRange: YearRange? = null,
    /** DOI identifiers found in the citation records. */
    val dois: List<String> = emptyList(),
    /** Keywords collected from all citation records. */
    val keywords: List<String> = emptyList(),
)
