// Generated by alef. Do not edit by hand.
// alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** dBASE (DBF) file metadata. */
data class DbfMetadata(
    /** Total number of data records in the DBF file. */
    val recordCount: Long = 0L,
    /** Number of field (column) definitions. */
    val fieldCount: Long = 0L,
    /** Descriptor for each field in the table schema. */
    val fields: List<DbfFieldInfo> = emptyList(),
)
