// Generated by alef. Do not edit by hand.
// alef:hash:ecd62fe5cf2cd8f8328ae99258ebd5e49253419ec89fd33fd9904d4205307faa
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** A single contiguous hunk in a unified diff. */
data class DiffHunk(
    /** Starting line number in the old content (0-indexed). */
    val fromLine: Long,
    /** Number of lines from the old content in this hunk. */
    val fromCount: Long,
    /** Starting line number in the new content (0-indexed). */
    val toLine: Long,
    /** Number of lines from the new content in this hunk. */
    val toCount: Long,
    /** Lines that make up this hunk. */
    @field:com.fasterxml.jackson.databind.annotation.JsonSerialize(contentAs = DiffLine::class)
    val lines: List<DiffLine> = emptyList(),
)
