// Generated by alef. Do not edit by hand.
// alef:hash:dcc92ea90af8d5bc8a609e43e1d5c4fa0281fdb468b8410303e0f01618f0078d
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
* Inference backend that an `EmbeddingPreset` runs on.
*
* `Onnx` presets require the `embeddings` feature (ONNX Runtime, not available on
* WASM/Android x86_64 emulator). `Static` presets require `static-embeddings`
* (pure-Rust model2vec inference, no ORT — the only dense-embedding backend
* available on `no-ort-target`).
*
* Defaults to `Onnx` via `#[serde(default)]` so every existing preset payload
* (which predates this field) keeps deserializing without change.
*/
enum class EmbeddingsEmbeddingBackend {
    /** ONNX Runtime transformer inference (the historical, default backend). */
    @com.fasterxml.jackson.annotation.JsonProperty("onnx") ONNX,
    /** Pure-Rust static (model2vec) inference — no ONNX Runtime. */
    @com.fasterxml.jackson.annotation.JsonProperty("static") STATIC;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            ONNX -> "onnx"
            STATIC -> "static"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): EmbeddingsEmbeddingBackend =
            when (value) {
                "onnx" -> ONNX
                "static" -> STATIC
                else -> throw IllegalArgumentException("Unknown EmbeddingsEmbeddingBackend value: $value")
            }
    }
}
