// Generated by alef. Do not edit by hand.
// alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Combined confidence on `[0, 1]`.
 *
 * When OCR did not run, the `ocr_aggregate` weight folds into `text_coverage`
 * so the weighted sum still totals 1.0.
 */
data class ExtractionConfidence(
    /** Fraction of pages with a usable text layer. */
    val textCoverage: Float,
    /** Mean OCR per-element recognition confidence when OCR ran; `null` when it did not. */
    val ocrAggregate: Float? = null,
    /** Whether the merged output validates against the preset schema. */
    val schemaCompliance: SchemaCompliance,
    /** Weighted blend in `[0, 1]`.  The value compared against the fallback threshold. */
    val combined: Float,
)
