// Generated by alef. Do not edit by hand.
// alef:hash:4577c9ebd804c0809b69d8562f2716f02f5a85942063765a38e4b6c1fb5c88b0
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * A footnote anchor reference in markdown text.
 *
 * Represents a `[^label]` use-site (not a definition).
 */
data class FootnoteAnchor(
    /** The label of the footnote reference (e.g., "1" in `[^1]`). */
    val label: String,
    /** Byte offset of the anchor in the markdown text. */
    val offset: Long,
)
