// Generated by alef. Do not edit by hand.
// alef:hash:4949fe4750595af66d93c9599afd8203f6eb4317062aa3575696f96acfa285d5
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Header/heading element metadata. */
data class HeaderMetadata(
    /** Header level: 1 (h1) through 6 (h6) */
    val level: Byte,
    /** Normalized text content of the header */
    val text: String,
    /** HTML id attribute if present */
    val id: String? = null,
    /** Document tree depth at the header element */
    val depth: Int,
    /** Byte offset in original HTML document */
    val htmlOffset: Int,
)
