// Generated by alef. Do not edit by hand.
// alef:hash:5f2945b053c810cf456eb384aa4a6eb94285c8e487d9dd54c65287a4eb5245e0
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Image element metadata. */
data class ImageMetadataType(
    /** Image source (URL, data URI, or SVG content) */
    val src: String,
    /** Alternative text from alt attribute */
    val alt: String? = null,
    /** Title attribute */
    val title: String? = null,
    /** Image type classification */
    val imageType: ImageType,
)
