// Generated by alef. Do not edit by hand.
// alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** JATS (Journal Article Tag Suite) metadata. */
data class JatsMetadata(
    /** Copyright statement from the article's `<permissions>` element. */
    val copyright: String? = null,
    /** Open-access license URI from the article's `<license>` element. */
    val license: String? = null,
    /** Publication history dates keyed by event type (e.g. `"received"`, `"accepted"`). */
    val historyDates: Map<String, String> = emptyMap(),
    /** Authors and contributors with their stated roles. */
    val contributorRoles: List<ContributorRole> = emptyList(),
)
