// Generated by alef. Do not edit by hand.
// alef:hash:de4849a812588cb0917cd1e50dc285b82acd659ee5299f00f46ad7457300ea6c
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Configuration for an LLM provider/model via liter-llm.
 *
 * Each feature (VLM OCR, VLM embeddings, structured extraction) carries
 * its own `LlmConfig`, allowing different providers per feature.
 *
 * `Debug` is implemented by hand so `api_key`, header values, and the AWS
 * credentials in `BedrockConfig` are never printed.
 */
data class LlmConfig(
    /**
     * Provider/model string using liter-llm routing format.
     *
     * Examples: `"openai/gpt-4o"`, `"anthropic/claude-sonnet-4-20250514"`,
     * `"groq/llama-3.1-70b-versatile"`.
     */
    val model: String = "",
    /**
     * API key for the provider. When `null`, liter-llm falls back to
     * the provider's standard environment variable (e.g., `OPENAI_API_KEY`).
     */
    val apiKey: String? = null,
    /** Custom base URL override for the provider endpoint. */
    val baseUrl: String? = null,
    /**
     * Request timeout in seconds. When `null`, liter-llm's built-in 60s default
     * applies, except the VLM OCR path which uses a 300s default (a single page
     * image transcription routinely exceeds 60s). Set explicitly to override.
     */
    val timeoutSecs: Long? = null,
    /** Maximum retry attempts (default: 3). */
    val maxRetries: Int? = null,
    /** Sampling temperature for generation tasks. */
    val temperature: Double? = null,
    /** Maximum tokens to generate. */
    val maxTokens: Long? = null,
    /**
     * Reasoning effort level for extended-thinking models, applied to individual
     * requests built from this config.
     *
     * Mirrors liter-llm's `ChatCompletionRequest.reasoning_effort`
     * (`types.chat.ReasoningEffort`). A request-time parameter like `temperature`/
     * `max_tokens` above, not a client-level setting — `into_client_builder` does not
     * map it. Accepted as a plain string — one of `"low"`, `"medium"`, `"high"`,
     * `"minimal"`, `"max"` (case-insensitive; liter-llm's own
     * `#[serde(rename_all = "lowercase")]` spelling) — rather than importing
     * liter-llm's enum, because this module compiles even when the `liter-llm`
     * feature is disabled. See `parse_reasoning_effort` for the
     * conversion into `liter_llm.ReasoningEffort`.
     */
    val reasoningEffort: String? = null,
    /**
     * Provider-specific extra parameters merged into the request body (guardrails,
     * safety settings, grounding config, etc.), applied to individual requests built
     * from this config.
     *
     * Mirrors liter-llm's `ChatCompletionRequest.extra_body`. A request-time
     * parameter like `temperature`/`max_tokens` above, not a client-level setting.
     */
    val extraBody: Any? = null,
    /**
     * Whether liter-llm should load provider credentials from environment variables.
     *
     * Mirrors liter-llm's `ClientConfigBuilder.load_env`. When `null`, liter-llm's
     * own default behavior applies.
     */
    val loadEnv: Boolean? = null,
    /**
     * Extra HTTP headers sent with every request to the provider.
     *
     * Mirrors liter-llm's `ClientConfigBuilder.header`, for gateways or providers
     * that require custom auth/routing headers.
     */
    val headers: Map<String, String>? = null,
    /**
     * Custom provider configurations, in addition to liter-llm's built-in providers.
     *
     * Mirrors liter-llm's `LlmConfig.providers`, for OpenAI-compatible gateways
     * and self-hosted model servers that are not in the built-in provider catalog.
     */
    val providers: List<LlmProviderConfig>? = null,
    /**
     * Response cache configuration.
     *
     * Mirrors liter-llm's `LlmConfig.cache`. Only takes effect when liter-llm's
     * `tower` feature is compiled in; otherwise the value is accepted but unused.
     *
     * Boxed for the same reason as `bedrock` (a4579589ac): `LlmConfig` is the payload
     * of `EmbeddingModelType.Llm` and `RerankerModelType.Llm`, whose other variants
     * are tens of bytes. Inlining this and the two sub-configs below pushed that
     * variant to 480 bytes and tripped `clippy.large_enum_variant` on the
     * `--features full` leg. ~keep
     */
    val cache: LlmCacheConfig? = null,
    /**
     * Budget enforcement configuration.
     *
     * Mirrors liter-llm's `LlmConfig.budget`. Only takes effect when liter-llm's
     * `tower` feature is compiled in; otherwise the value is accepted but unused.
     */
    val budget: LlmBudgetConfig? = null,
    /**
     * Per-model rate limiting configuration.
     *
     * Mirrors liter-llm's `LlmConfig.rate_limit`. Only takes effect when liter-llm's
     * `tower` feature is compiled in; otherwise the value is accepted but unused.
     */
    val rateLimit: LlmRateLimitConfig? = null,
    /**
     * Enable per-request cost tracking.
     *
     * Mirrors liter-llm's `LlmConfig.cost_tracking`. Only takes effect when
     * liter-llm's `tower` feature is compiled in; otherwise the value is accepted
     * but unused.
     */
    val costTracking: Boolean? = null,
    /**
     * Enable OpenTelemetry-compatible tracing spans.
     *
     * Mirrors liter-llm's `LlmConfig.tracing`. Only takes effect when liter-llm's
     * `tower` feature is compiled in; otherwise the value is accepted but unused.
     */
    val tracing: Boolean? = null,
    /**
     * Cooldown duration after transient errors, in seconds.
     *
     * Mirrors liter-llm's `LlmConfig.cooldown_secs`. Only takes effect when
     * liter-llm's `tower` feature is compiled in; otherwise the value is accepted
     * but unused.
     */
    val cooldownSecs: Long? = null,
    /**
     * Background health check interval, in seconds.
     *
     * Mirrors liter-llm's `LlmConfig.health_check_secs`. Only takes effect when
     * liter-llm's `tower` feature is compiled in; otherwise the value is accepted
     * but unused.
     */
    val healthCheckSecs: Long? = null,
    /**
     * AWS Bedrock settings (region, cross-region routing, explicit credentials).
     *
     * Only consulted for `bedrock/`-prefixed models. When `null` — or when an
     * individual field inside it is `null` — liter-llm falls back to the standard
     * AWS environment variables and the default credential chain.
     */
    val bedrock: BedrockConfig? = null,
    /**
     * Managed OAuth2/STS credential provider for auth modes liter-llm cannot express via a
     * static `api_key` — Azure AD, Vertex AI OAuth2, Vertex AI Application Default
     * Credentials, and AWS STS Web Identity (EKS IRSA) for Bedrock.
     *
     * Mirrors liter-llm's `client.ClientConfigBuilder.credential_provider`, which takes an
     * `Arc<dyn liter_llm.auth.CredentialProvider>` trait object — that cannot appear in a
     * serde DTO. Every `CredentialProviderConfig` variant is plain data instead, so it
     * round-trips through TOML/JSON/YAML and every language binding like the rest of
     * `LlmConfig`.
     *
     * Inert on `wasm32`: `crate.llm` (the module that reads this field —
     * `build_credential_provider` and friends) is compiled out
     * entirely on that target, via the crate-root `#[cfg(all(feature = "liter-llm",
     * not(target_arch = "wasm32")))] pub mod llm;` gate in `lib.rs`. Every variant needs
     * liter-llm's `native-http`-backed auth modules, and wasm32 builds request only
     * `wasm-http` (see the `liter-llm` dependency comment in Cargo.toml), so there is no
     * code path left on that target to construct a provider from this field, or to reject
     * it. This type (`core.config.llm`) has no `liter-llm` dependency itself and compiles
     * on every target, so setting this field on a wasm32 build is accepted by serde and
     * silently ignored — a plain no-op, not a `Validation`. Reject a
     * wasm32 build that sets this field yourself if that silence is a problem for your use
     * case; xberg does not do it for you.
     *
     * GitHub Copilot's device-flow provider has no variant here: it takes no configuration at
     * all (`liter_llm.auth.github_copilot.GithubCopilotCredentialProvider.new` accepts only
     * an HTTP client) and drives an interactive terminal prompt, so it cannot be expressed as
     * data. A Rust embedder who needs it — or any other fully custom `CredentialProvider` — can
     * call `xberg.llm.client.create_client_with_credential_provider` directly with a
     * `liter-llm` dependency of their own.
     */
    @field:com.fasterxml.jackson.databind.annotation.JsonSerialize(`as` = CredentialProviderConfig::class)
    val credentialProvider: CredentialProviderConfig? = null,
)
