// Generated by alef. Do not edit by hand.
// alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Combined paths to all models needed for OCR (backward compatibility). */
data class ModelPaths(
    /** Exact path to the detection ONNX model in the Hugging Face snapshot. */
    val detModel: String,
    /** Exact path to the classification ONNX model in the Hugging Face snapshot. */
    val clsModel: String,
    /** Exact path to the recognition ONNX model in the Hugging Face snapshot. */
    val recModel: String,
    /** Path to the character dictionary file. */
    val dictFile: String,
)
