// Generated by alef. Do not edit by hand.
// alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Table detected via OCR.
 *
 * Represents a table structure recognized during OCR processing.
 */
data class OcrTable(
    /** Table cells as a 2D vector (rows × columns) */
    val cells: List<List<String>> = emptyList(),
    /** Markdown representation of the table */
    val markdown: String,
    /** Page number where the table was found (1-indexed) */
    val pageNumber: Int,
    /** Bounding box of the table in pixel coordinates (from OCR word positions). */
    val boundingBox: OcrTableBoundingBox? = null,
)
