// Generated by alef. Do not edit by hand.
// alef:hash:7d263f3a968074560e5e393ac4e3b11e26a6f126021e0f1fac373bfdd19822e1

package io.xberg

object PostProcessorBridge {
    private val registered = mutableMapOf<String, IPostProcessor>()

    fun register(impl: IPostProcessor): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterPostProcessor(PostProcessorJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterPostProcessor(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearPostProcessors()
    }

    fun getAll(): Map<String, IPostProcessor> = registered.toMap()
}
