// Generated by alef. Do not edit by hand.
// alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * The content changes that make up a single revision.
 *
 * For insertions and deletions the `content` field carries the added/removed
 * lines as `DiffLine.Added` / `DiffLine.Removed` entries. For format
 * changes, `property_changes` carries normalized before/after formatting
 * values when the source document exposes them.
 */
data class RevisionDelta(
    /** Line-level content changes for this revision. */
    @field:com.fasterxml.jackson.databind.annotation.JsonSerialize(contentAs = DiffLine::class)
    val content: List<DiffLine> = emptyList(),
    /** Cell-level table changes for this revision. */
    val tableChanges: List<CellChange> = emptyList(),
    /** Formatting or metadata property changes for this revision. */
    val propertyChanges: List<PropertyChange> = emptyList(),
)
