// Generated by alef. Do not edit by hand.
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Result of parsing a structured data file (JSON, JSONL, YAML, or TOML). */
data class StructuredDataResult(
    /** The extracted text content, formatted for readability. */
    val content: String,
    /** The source format identifier (e.g. `"json"`, `"yaml"`, `"toml"`). */
    val format: String,
    /** Key-value metadata extracted from recognized text fields. */
    val metadata: Map<String, String> = emptyMap(),
    /** JSON paths of fields that were classified as text-bearing. */
    val textFields: List<String> = emptyList(),
)
