// Generated by alef. Do not edit by hand.
// alef:hash:9b026fac016b32a70e62d66fdaaabf6341f29ba1a211d6fe3877e1ba9a151761
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Structured data (Schema.org, microdata, RDFa) block. */
data class StructuredData(
    /** Type of structured data */
    val dataType: StructuredDataType,
    /** Raw JSON string representation */
    val rawJson: String,
    /** Schema type if detectable (e.g., "Article", "Event", "Product") */
    val schemaType: String? = null,
)
