// Generated by alef. Do not edit by hand.
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Summarisation strategy. */
enum class SummaryStrategy {
    /**
     * Pure-Rust extractive summary (TextRank over the chunk graph). Deterministic,
     * fast, no external service required.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("extractive") EXTRACTIVE,
    /**
     * Abstractive summary produced by liter-llm. Requires `liter-llm` feature and
     * a configured `LlmConfig`. Token usage is captured in
     * `ExtractedDocument.llm_usage`.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("abstractive") ABSTRACTIVE;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
    when (this) {
        EXTRACTIVE -> "extractive"
        ABSTRACTIVE -> "abstractive"
    }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): SummaryStrategy =
        when (value) {
            "extractive" -> EXTRACTIVE
            "abstractive" -> ABSTRACTIVE
            else -> throw IllegalArgumentException("Unknown SummaryStrategy value: $value")
        }
    }
}
