// Generated by alef. Do not edit by hand.
// alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Plain text and Markdown extraction result.
 *
 * Contains the extracted text along with statistics and,
 * for Markdown files, structural elements like headers and links.
 */
data class TextExtractionResult(
    /** Extracted text content */
    val content: String,
    /** Number of lines */
    val lineCount: Long,
    /** Number of words */
    val wordCount: Long,
    /** Number of characters */
    val characterCount: Long,
    /** Markdown headers (text only, Markdown files only) */
    val headers: List<String>? = null,
)
