// Generated by alef. Do not edit by hand.
// alef:hash:ba94fe4cec719c31f8ac484fcc2aba1d30db0f87dea8b1b6d0257417a4a260e2

package io.xberg

object TokenizerBackendBridge {
    private val registered = mutableMapOf<String, ITokenizerBackend>()

    fun register(impl: ITokenizerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterTokenizerBackend(TokenizerBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterTokenizerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearTokenizerBackends()
    }

    fun getAll(): Map<String, ITokenizerBackend> = registered.toMap()
}
