// Generated by alef. Do not edit by hand.
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34

package io.xberg

object TokenizerBackendBridge {
    private val registered = mutableMapOf<String, ITokenizerBackend>()

    fun register(impl: ITokenizerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterTokenizerBackend(TokenizerBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterTokenizerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearTokenizerBackends()
    }

    fun getAll(): Map<String, ITokenizerBackend> = registered.toMap()
}
