// Generated by alef. Do not edit by hand.
// alef:hash:d1848f4fcf5b21064de077b392f632ff3aab70f8082291ad6f4177dbf707969e

package io.xberg

class XbergBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
