// DO NOT EDIT - auto-generated by alef
// alef:hash:ecd62fe5cf2cd8f8328ae99258ebd5e49253419ec89fd33fd9904d4205307faa
package io.xberg;

/**
 * The meta-schema itself failed to compile.
 */
public class BadMetaSchemaException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BadMetaSchemaException with the given message. */
  public BadMetaSchemaException(final String message) { super(message); }

  /** Creates a new BadMetaSchemaException with the given message and cause. */
  public BadMetaSchemaException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
