// DO NOT EDIT - auto-generated by alef
// alef:hash:2e8cf86718aeb5a4b108a97e79d1a5f9f0ba9709a6a7f6bd9d8c92d64568a83d
package io.xberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheException with the given message. */
  public CacheException(final String message) {
    super(message);
  }

  /** Creates a new CacheException with the given message and cause. */
  public CacheException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
