// DO NOT EDIT - auto-generated by alef
// alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
package io.xberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
