// DO NOT EDIT - auto-generated by alef
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
package io.xberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheException with the given message. */
  public CacheException(final String message) { super(message); }

  /** Creates a new CacheException with the given message and cause. */
  public CacheException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
