// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/**
 * Chunk-classification enrichment knob: how to multi-label individual chunks.
 *
 * Operates on {@code ExtractedDocument.chunks} in place — the caller must have
 * already produced chunks (e.g. via {@code ExtractionConfig.chunking}) for this
 * stage to have any effect; a document with no chunks is a no-op.
 */
public record ChunkClassificationEnrichmentConfig(ChunkClassificationConfig config) {
}
