// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b2c29ab80fb9cdb8c5190a7808ad862ad890f416ad887092447b282a5b1b69e0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/**
 * Chunk-classification enrichment knob: how to multi-label individual chunks.
 *
 * Operates on {@code ExtractedDocument.chunks} in place — the caller must have
 * already produced chunks (e.g. via {@code ExtractionConfig.chunking}) for this
 * stage to have any effect; a document with no chunks is a no-op.
 */
public record ChunkClassificationEnrichmentConfig(ChunkClassificationConfig config) {
}
