// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3437f3f25de23449b643e9fa4d9c6498ebc166f3b58ebc78a2d876badf537d6f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/**
 * Chunk-classification enrichment knob: how to multi-label individual chunks.
 *
 * Operates on {@code ExtractedDocument.chunks} in place — the caller must have
 * already produced chunks (e.g. via {@code ExtractionConfig.chunking}) for this
 * stage to have any effect; a document with no chunks is a no-op.
 */
public record
    ChunkClassificationEnrichmentConfig(ChunkClassificationConfig config) {}
