// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:09aef397751d19e6b2c5930337edc865cef5752cf7c5ae2bab144cd672e494f8
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/** Exception thrown when an FFI value conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends XbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(1, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
