// DO NOT EDIT - auto-generated by alef
// alef:hash:27b14662489dbd72bffe76d749cce63acd51fb05b9d0eea856452c7d4c92c223
package io.xberg;

/**
 * The file validates but cannot be deserialized into [`Preset`].
 */
public class DeserializeException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeserializeException with the given message. */
  public DeserializeException(final String message) { super(message); }

  /** Creates a new DeserializeException with the given message and cause. */
  public DeserializeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
