// DO NOT EDIT - auto-generated by alef
// alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
package io.xberg;

/**
 * The file validates but cannot be deserialized into [`Preset`].
 */
public class DeserializeException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeserializeException with the given message. */
  public DeserializeException(final String message) { super(message); }

  /** Creates a new DeserializeException with the given message and cause. */
  public DeserializeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
