// DO NOT EDIT - auto-generated by alef
// alef:hash:0b25f8d986f4622ecac7469fab12f950f292c97a76d9e8c8211cd7fd00684c80
package io.xberg;

/**
 * The embedding model or embedding pipeline returned an error.
 */
public class EmbeddingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new EmbeddingException with the given message. */
  public EmbeddingException(final String message) {
    super(message);
  }

  /** Creates a new EmbeddingException with the given message and cause. */
  public EmbeddingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
