// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2e7981d0316a6258f9123d342e520c06d9f9989752131e0f731e2b0b52f09f62
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

import java.util.List;

/**
 * Path A Bridge implementation for IEmbeddingBackend.
 *
 * Wraps a user-supplied implementation and delegates all method calls.
 * This adapter conforms to the hand-authored sealed interface.
 */
public final class EmbeddingBackendAdapter implements IEmbeddingBackend {
    private final IEmbeddingBackend impl;

    public EmbeddingBackendAdapter(IEmbeddingBackend impl) {
        this.impl = impl;
    }

    @Override
    public String name() {
        return impl.name();
    }

    @Override
    public String version() {
        return impl.version();
    }

    @Override
    public void initialize() throws Exception {
        impl.initialize();
    }

    @Override
    public void shutdown() throws Exception {
        impl.shutdown();
    }

    @Override
    public long dimensions() throws Exception {
        return impl.dimensions();
    }

    @Override
    public List<List<Float>> embed(List<String> texts) throws Exception {
        return impl.embed(texts);
    }


}
