// DO NOT EDIT - auto-generated by alef
// alef:hash:ba94fe4cec719c31f8ac484fcc2aba1d30db0f87dea8b1b6d0257417a4a260e2
package io.xberg;

/**
 * The embedding model or embedding pipeline returned an error.
 */
public class EmbeddingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new EmbeddingException with the given message. */
  public EmbeddingException(final String message) { super(message); }

  /** Creates a new EmbeddingException with the given message and cause. */
  public EmbeddingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
