// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Error metadata (for batch operations).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ErrorMetadata.Builder.class)
public record ErrorMetadata(@JsonProperty("error_type") String errorType,
                            @JsonProperty("message") String message) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }

  // CPD-OFF
  /** Jackson builder for ErrorMetadata deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    @JsonProperty("error_type") private String errorType;
    private String message;

    /** Sets the errorType field. */
    @JsonProperty("error_type")
    public Builder withErrorType(final String value) {
      this.errorType = value;
      return this;
    }

    /** Sets the message field. */
    @JsonProperty("message")
    public Builder withMessage(final String value) {
      this.message = value;
      return this;
    }

    /** Constructs a ErrorMetadata instance from the builder's current state. */
    public ErrorMetadata build() {
      return new ErrorMetadata(errorType, message);
    }
  }
  // CPD-ON
}
