// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ONNX Runtime execution provider type.
 *
 * Determines which hardware backend is used for model inference.
 * {@code Auto} (default) selects the best available provider per platform.
 */
@SuppressWarnings("PMD")
public enum ExecutionProviderType {
  /**
   * Auto-select: CoreML on macOS, CUDA on Linux, CPU elsewhere.
   */
  Auto("auto"),
  /**
   * CPU execution provider (always available).
   */
  Cpu("cpu"),
  /**
   * Apple CoreML (macOS/iOS Neural Engine + GPU).
   */
  CoreMl("coreml"),
  /**
   * NVIDIA CUDA GPU acceleration.
   */
  Cuda("cuda"),
  /**
   * NVIDIA TensorRT (optimized CUDA inference).
   */
  TensorRt("tensorrt");

  /** The string value. */
  private final String value;

  ExecutionProviderType(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static ExecutionProviderType fromValue(final String value) {
    for (ExecutionProviderType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown ExecutionProviderType value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
