// DO NOT EDIT - auto-generated by alef
// alef:hash:c3791adf1b839bfcd1fa99494b64a3750f0f4fb72aaafa3742ec512dd3694e34
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new HeuristicsErrorException with the given message. */
  public HeuristicsErrorException(final String message) { super(message); }

  /**
   * Creates a new HeuristicsErrorException with the given message and cause.
   */
  public HeuristicsErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
