// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3d9b13384087fab6fc1796724185add5b6e2f484ab0fefb168acec2f2c3cca20
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

import java.util.List;

/**
 * Bridge interface for the EmbeddingBackend plugin system.
 *
 * Implementations are wrapped by EmbeddingBackendBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IEmbeddingBackend {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** dimensions. */    long dimensions() throws Exception;

/** embed. */    List<List<Float>> embed(List<String> texts) throws Exception;
}
