// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:335f9a5767bba42f3008665d8a5e9948b8c3a37a06df4b2c851c9d2eb4097c54
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

import java.util.List;

/**
 * Bridge interface for the EmbeddingBackend plugin system.
 *
 * Implementations are wrapped by EmbeddingBackendBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IEmbeddingBackend {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** dimensions. */    long dimensions() throws Exception;

/** embed. */    List<List<Float>> embed(List<String> texts) throws Exception;
}
