// DO NOT EDIT - auto-generated by alef
// alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
package io.xberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ImageProcessingException with the given message. */
  public ImageProcessingException(final String message) { super(message); }

  /**
   * Creates a new ImageProcessingException with the given message and cause.
   */
  public ImageProcessingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
