// DO NOT EDIT - auto-generated by alef
// alef:hash:2e1db2b3691405aa768a1bee7ef18fe1dddd1f3ee37b34aa21cdeac1a39d0fa7
package io.xberg;

/**
 * A filesystem I/O error occurred while reading a preset directory.
 */
public class IoException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoException with the given message. */
  public IoException(final String message) {
    super(message);
  }

  /** Creates a new IoException with the given message and cause. */
  public IoException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
