// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1f4a6b9250594eb96adfd427fd56d962d5f19052b938b9a1c23659e1734a50dc
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;


/**
 * Bridge interface for the Renderer plugin system.
 *
 * Implementations are wrapped by RendererBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IRenderer {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** render_result. */    String render_result(ExtractedDocument result) throws Exception;
}
