// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ba3ba70e49544c7de597010511ae8a9a3c93b15ec527da7f2bbe7ad32cf6d027
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;


/**
 * Bridge interface for the Renderer plugin system.
 *
 * Implementations are wrapped by RendererBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IRenderer {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** render_result. */    String render_result(ExtractedDocument result) throws Exception;
}
