// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Link rendering style in Markdown output.
 *
 * Controls whether links and images use inline {@code [text](url)} syntax or
 * reference-style {@code [text][1]} syntax with definitions collected at the end.
 */
@SuppressWarnings("PMD")
public enum LinkStyle {
    /**
     * Inline links: {@code [text](url)}. Default.
     */
    Inline("inline"),
    /**
     * Reference-style links: {@code [text][1]} with {@code [1]: url} at end of document.
     */
    Reference("reference");


    /** The string value. */
    private final String value;

    LinkStyle(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static LinkStyle fromValue(final String value) {
        for (LinkStyle e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown LinkStyle value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
