// DO NOT EDIT - auto-generated by alef
// alef:hash:555693b8919ee5349f15f42f35c639d27b2b3556614c152d9ce4b6f88259cc9c
package io.xberg;

/**
 * Errors produced while loading or validating a preset file.
 */
public class LoadErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new LoadErrorException with the given message. */
  public LoadErrorException(final String message) {
    super(message);
  }

  /** Creates a new LoadErrorException with the given message and cause. */
  public LoadErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
