// DO NOT EDIT - auto-generated by alef
// alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
package io.xberg;

/**
 * Errors produced while loading or validating a preset file.
 */
public class LoadErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new LoadErrorException with the given message. */
  public LoadErrorException(final String message) { super(message); }

  /** Creates a new LoadErrorException with the given message and cause. */
  public LoadErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
