// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Hierarchical level of an OCR element.
 *
 * Maps to Tesseract's page segmentation hierarchy and provides
 * equivalent semantics for PaddleOCR.
 */
@SuppressWarnings("PMD")
public enum OcrElementLevel {
  /**
   * Individual word
   */
  Word("word"),
  /**
   * Line of text (default for PaddleOCR)
   */
  Line("line"),
  /**
   * Paragraph or text block
   */
  Block("block"),
  /**
   * Page-level element
   */
  Page("page");

  /** The string value. */
  private final String value;

  OcrElementLevel(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static OcrElementLevel fromValue(final String value) {
    for (OcrElementLevel e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown OcrElementLevel value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
