// DO NOT EDIT - auto-generated by alef
// alef:hash:de4849a812588cb0917cd1e50dc285b82acd659ee5299f00f46ad7457300ea6c
package io.xberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OcrException with the given message. */
  public OcrException(final String message) { super(message); }

  /** Creates a new OcrException with the given message and cause. */
  public OcrException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
