// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bf343782b30e722cc2e21029ec9538f780eb26075f1335ab017c3e0a01e372f4
// To regenerate: alef generate
// To verify freshness: alef verify

/**
 * High-performance document intelligence library
 */
package io.xberg;
