// DO NOT EDIT - auto-generated by alef
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
package io.xberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) { super(message); }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
