// DO NOT EDIT - auto-generated by alef
// alef:hash:2ea65f3e23f7dec4bb1638353b2f257ba5abe08dc1eec0c60bd90e5c327a3445
package io.xberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) {
    super(message);
  }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
