// DO NOT EDIT - auto-generated by alef
// alef:hash:67e068ab56495acb71bbb36b97e5d1caa1756b12b05aed54a64236363f403c3f
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfAnalysisErrorException with the given message. */
  public PdfAnalysisErrorException(final String message) { super(message); }

  /**
   * Creates a new PdfAnalysisErrorException with the given message and cause.
   */
  public PdfAnalysisErrorException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
