// DO NOT EDIT - auto-generated by alef
// alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new PdfAnalysisErrorException with the given message. */
    public PdfAnalysisErrorException(final String message) {
        super(message);
    }

    /** Creates a new PdfAnalysisErrorException with the given message and cause. */
    public PdfAnalysisErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
