// DO NOT EDIT - auto-generated by alef
// alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfAnalysisErrorException with the given message. */
  public PdfAnalysisErrorException(final String message) { super(message); }

  /**
   * Creates a new PdfAnalysisErrorException with the given message and cause.
   */
  public PdfAnalysisErrorException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
