// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1567f07e32be059dfb45f7d2b5c5637070c2e083517ceee5503d99c9c0f0fb34
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import org.jspecify.annotations.Nullable;

/**
 * PII categories the pattern engine recognises.
 */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@JsonDeserialize(using = PiiCategoryDeserializer.class)
@JsonSerialize(using = PiiCategorySerializer.class)
public sealed interface PiiCategory {

  /**
   * Email address (e.g. {@code user@example.com}).
   */
  record Email() implements PiiCategory {}

  /**
   * Phone number in any common format.
   */
  record Phone() implements PiiCategory {}

  /**
   * US Social Security Number.
   */
  record Ssn() implements PiiCategory {}

  /**
   * Payment card number (Visa, Mastercard, Amex, etc.).
   */
  record CreditCard() implements PiiCategory {}

  /**
   * Postal / ZIP code.
   */
  record PostalCode() implements PiiCategory {}

  /**
   * IPv4 or IPv6 address.
   */
  record IpAddress() implements PiiCategory {}

  /**
   * International Bank Account Number.
   */
  record Iban() implements PiiCategory {}

  /**
   * SWIFT / BIC bank identifier code.
   */
  record SwiftBic() implements PiiCategory {}

  /**
   * Date of birth.
   */
  record DateOfBirth() implements PiiCategory {}

  /**
   * Person name, surfaced by the optional NER backend.
   */
  record Person() implements PiiCategory {}

  /**
   * Organization name, surfaced by the optional NER backend.
   */
  record Organization() implements PiiCategory {}

  /**
   * Location, surfaced by the optional NER backend.
   */
  record Location() implements PiiCategory {}

  /**
   * Caller-supplied custom category (e.g. internal employee IDs).
   *
   * Surfaced by the redaction engine when a hit comes from
   * RedactionConfig.custom_terms(crate.core.config.redaction.RedactionConfig.custom_terms)
   * or
   * RedactionConfig.custom_patterns(crate.core.config.redaction.RedactionConfig.custom_patterns).
   * The string is the label passed alongside the term/pattern. Use those
   * fields rather than constructing {@code Custom} directly via the
   * {@code categories} filter — the pattern engine cannot detect arbitrary text
   * from a category name alone.
   */
  record Custom(String value) implements PiiCategory {}

  /** Returns the Custom data if this is a Custom variant, otherwise null. */
  default @Nullable String custom() {
    return this instanceof Custom variant ? variant.value() : null;
  }
}

/** Custom deserializer for sealed interface with unwrapped variants. */
class PiiCategoryDeserializer extends StdDeserializer<PiiCategory> {
  private static final long serialVersionUID = 1L;

  PiiCategoryDeserializer() { super(PiiCategory.class); }

  @Override
  @SuppressWarnings("PMD.CyclomaticComplexity")
  public PiiCategory deserialize(final JsonParser parser,
                                 final DeserializationContext ctx)
      throws java.io.IOException {
    final com.fasterxml.jackson.databind.JsonNode wire =
        parser.getCodec().readTree(parser);
    if (wire.isTextual()) {
      return switch (wire.asText()) {
        case "email" -> new PiiCategory.Email();
        case "phone" -> new PiiCategory.Phone();
        case "ssn" -> new PiiCategory.Ssn();
        case "credit_card" -> new PiiCategory.CreditCard();
        case "postal_code" -> new PiiCategory.PostalCode();
        case "ip_address" -> new PiiCategory.IpAddress();
        case "iban" -> new PiiCategory.Iban();
        case "swift_bic" -> new PiiCategory.SwiftBic();
        case "date_of_birth" -> new PiiCategory.DateOfBirth();
        case "person" -> new PiiCategory.Person();
        case "organization" -> new PiiCategory.Organization();
        case "location" -> new PiiCategory.Location();
        default ->
          throw new com.fasterxml.jackson.databind.JsonMappingException(
              parser, "Unknown PiiCategory unit variant: " + wire.asText());
      };
    }
    if (!wire.isObject() || wire.size() != 1) {
      throw new com.fasterxml.jackson.databind.JsonMappingException(
          parser, "Expected one externally tagged PiiCategory variant");
    }
    final String tagValue = wire.fieldNames().next();
    final com.fasterxml.jackson.databind.JsonNode contentNode =
        wire.get(tagValue);

    return switch (tagValue) {
      case "email" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "phone" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "ssn" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "credit_card" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "postal_code" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "ip_address" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "iban" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "swift_bic" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "date_of_birth" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "person" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "organization" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "location" ->
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Externally tagged unit variants must be strings");
      case "custom" ->
        new PiiCategory.Custom(ctx.readTreeAsValue(contentNode, String.class));
      default -> {
        throw new com.fasterxml.jackson.databind.JsonMappingException(
            parser, "Unknown PiiCategory discriminator: " + tagValue);
      }
    };
  }
}

/** Custom serializer for serde's externally tagged enum shape. */
class PiiCategorySerializer extends StdSerializer<PiiCategory> {
  private static final long serialVersionUID = 1L;
  /** ObjectMapper for serializing inner variant values. */
  private static final com.fasterxml.jackson.databind.ObjectMapper MAPPER =
      createMapper();

  private static com.fasterxml.jackson.databind.ObjectMapper createMapper() {
    var mapper =
        new com.fasterxml.jackson.databind.ObjectMapper()
            .registerModule(
                new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
            .setPropertyNamingStrategy(com.fasterxml.jackson.databind
                                           .PropertyNamingStrategies.SNAKE_CASE)
            .setSerializationInclusion(
                com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL);
    return JsonMapperFactory.withNativePathSerialization(mapper);
  }

  /** Creates a new PiiCategorySerializer. */
  PiiCategorySerializer() { super(PiiCategory.class); }

  @Override
  @SuppressWarnings("PMD.CyclomaticComplexity")
  public void serialize(PiiCategory value, JsonGenerator gen,
                        SerializerProvider provider)
      throws java.io.IOException {
    String tag;
    Object inner;
    if (value instanceof PiiCategory.Email variantEmail) {
      tag = "email";
      inner = null;
    } else if (value instanceof PiiCategory.Phone variantPhone) {
      tag = "phone";
      inner = null;
    } else if (value instanceof PiiCategory.Ssn variantSsn) {
      tag = "ssn";
      inner = null;
    } else if (value instanceof PiiCategory.CreditCard variantCreditCard) {
      tag = "credit_card";
      inner = null;
    } else if (value instanceof PiiCategory.PostalCode variantPostalCode) {
      tag = "postal_code";
      inner = null;
    } else if (value instanceof PiiCategory.IpAddress variantIpAddress) {
      tag = "ip_address";
      inner = null;
    } else if (value instanceof PiiCategory.Iban variantIban) {
      tag = "iban";
      inner = null;
    } else if (value instanceof PiiCategory.SwiftBic variantSwiftBic) {
      tag = "swift_bic";
      inner = null;
    } else if (value instanceof PiiCategory.DateOfBirth variantDateOfBirth) {
      tag = "date_of_birth";
      inner = null;
    } else if (value instanceof PiiCategory.Person variantPerson) {
      tag = "person";
      inner = null;
    } else if (value instanceof PiiCategory.Organization variantOrganization) {
      tag = "organization";
      inner = null;
    } else if (value instanceof PiiCategory.Location variantLocation) {
      tag = "location";
      inner = null;
    } else if (value instanceof PiiCategory.Custom variantCustom) {
      tag = "custom";
      inner = variantCustom.value();
    } else {
      throw new com.fasterxml.jackson.databind.JsonMappingException(
          gen, "Unknown PiiCategory variant: " + value.getClass().getName());
    }

    if (inner == null) {
      gen.writeString(tag);
      return;
    }
    gen.writeStartObject();
    gen.writeFieldName(tag);
    gen.writeTree(MAPPER.valueToTree(inner));
    gen.writeEndObject();
  }
}
