// DO NOT EDIT - auto-generated by alef
// alef:hash:7a4e1172a50174f98c0344f1c306b4262ce36ed628adf0fc84c858651d27a420
package io.xberg;

/**
 * A registered plugin returned an error during extraction.
 */
public class PluginException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PluginException with the given message. */
  public PluginException(final String message) { super(message); }

  /** Creates a new PluginException with the given message and cause. */
  public PluginException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
