// DO NOT EDIT - auto-generated by alef
// alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
package io.xberg;

/**
 * The reranker model or reranking pipeline returned an error.
 *
 * Since v5.0.0.
 */
public class RerankingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RerankingException with the given message. */
  public RerankingException(final String message) { super(message); }

  /** Creates a new RerankingException with the given message and cause. */
  public RerankingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
