// DO NOT EDIT - auto-generated by alef
// alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
package io.xberg;

/**
 * The reranker model or reranking pipeline returned an error.
 *
 * Since v5.0.0.
 */
public class RerankingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RerankingException with the given message. */
  public RerankingException(final String message) { super(message); }

  /** Creates a new RerankingException with the given message and cause. */
  public RerankingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
