// DO NOT EDIT - auto-generated by alef
// alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
package io.xberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ResolveErrorException with the given message. */
  public ResolveErrorException(final String message) { super(message); }

  /** Creates a new ResolveErrorException with the given message and cause. */
  public ResolveErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
