// DO NOT EDIT - auto-generated by alef
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
package io.xberg;

/**
 * A custom schema override was supplied but is not a JSON object.
 */
public class SchemaNotObjectException extends ResolveErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaNotObjectException with the given message. */
  public SchemaNotObjectException(final String message) { super(message); }

  /**
   * Creates a new SchemaNotObjectException with the given message and cause.
   */
  public SchemaNotObjectException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
