// DO NOT EDIT - auto-generated by alef
// alef:hash:079376bb0843afa36ec7d4d9c540f36a97e3194abb697cb10187cc1715d6b66d
package io.xberg;

/**
 * The file parses as JSON but does not validate against the meta-schema.
 */
public class SchemaValidationException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaValidationException with the given message. */
  public SchemaValidationException(final String message) { super(message); }

  /**
   * Creates a new SchemaValidationException with the given message and cause.
   */
  public SchemaValidationException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
