// DO NOT EDIT - auto-generated by alef
// alef:hash:c257c1321506b1f3029e4c1b7754280155b10cfedcc0e622fa1200617b818a00
package io.xberg;

/**
 * The file parses as JSON but does not validate against the meta-schema.
 */
public class SchemaValidationException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaValidationException with the given message. */
  public SchemaValidationException(final String message) { super(message); }

  /**
   * Creates a new SchemaValidationException with the given message and cause.
   */
  public SchemaValidationException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
