// DO NOT EDIT - auto-generated by alef
// alef:hash:41105a5db21cb9241b8e372890031fd3eaa44c52773aaf42ba0566d7f1b48d90
package io.xberg;

/**
 * A custom schema override was supplied but is not a JSON object.
 */
public class SchemaNotObjectException extends ResolveErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaNotObjectException with the given message. */
  public SchemaNotObjectException(final String message) { super(message); }

  /**
   * Creates a new SchemaNotObjectException with the given message and cause.
   */
  public SchemaNotObjectException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
