// DO NOT EDIT - auto-generated by alef
// alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
package io.xberg;

/**
 * A custom schema override was supplied but is not a JSON object.
 */
public class SchemaNotObjectException extends ResolveErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaNotObjectException with the given message. */
  public SchemaNotObjectException(final String message) { super(message); }

  /**
   * Creates a new SchemaNotObjectException with the given message and cause.
   */
  public SchemaNotObjectException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
