// DO NOT EDIT - auto-generated by alef
// alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
package io.xberg;

/**
 * The file parses as JSON but does not validate against the meta-schema.
 */
public class SchemaValidationException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new SchemaValidationException with the given message. */
    public SchemaValidationException(final String message) {
        super(message);
    }

    /** Creates a new SchemaValidationException with the given message and cause. */
    public SchemaValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
