// DO NOT EDIT - auto-generated by alef
// alef:hash:ecd62fe5cf2cd8f8328ae99258ebd5e49253419ec89fd33fd9904d4205307faa
package io.xberg;

/**
 * A security policy was violated (e.g. zip bomb, oversized archive).
 */
public class SecurityException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SecurityException with the given message. */
  public SecurityException(final String message) { super(message); }

  /** Creates a new SecurityException with the given message and cause. */
  public SecurityException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
