// DO NOT EDIT - auto-generated by alef
// alef:hash:60f5bb4630522e7c5482f8e26b8a7786c13ef2d329007f7615ae4997ae233789
package io.xberg;

/**
 * A security policy was violated (e.g. zip bomb, oversized archive).
 */
public class SecurityException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SecurityException with the given message. */
  public SecurityException(final String message) {
    super(message);
  }

  /** Creates a new SecurityException with the given message and cause. */
  public SecurityException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
