// DO NOT EDIT - auto-generated by alef
// alef:hash:792891f7f4f1517cf1c8aded951d3dd2e09a4c7cfff9dca979a734cceee84ada
package io.xberg;

/**
 * A security policy was violated (e.g. zip bomb, oversized archive).
 */
public class SecurityException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
