// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:de4849a812588cb0917cd1e50dc285b82acd659ee5299f00f46ad7457300ea6c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Structured data type classification.
 */
@SuppressWarnings("PMD")
public enum StructuredDataType {
  /**
   * JSON-LD structured data
   */
  JsonLd("json-ld"),
  /**
   * Microdata
   */
  Microdata("microdata"),
  /**
   * RDFa
   */
  RDFa("rdfa");

  /** The string value. */
  private final String value;

  StructuredDataType(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static StructuredDataType fromValue(final String value) {
    for (StructuredDataType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown StructuredDataType value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
