// DO NOT EDIT - auto-generated by alef
// alef:hash:640498c28465cd7c3da00bb214bc3827aa86515cadfae0af07488506f37314c9
package io.xberg;

/**
 * The extraction operation exceeded the configured time limit.
 */
public class TimeoutException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
