// DO NOT EDIT - auto-generated by alef
// alef:hash:dc601a47d5596a4fb6027b2ebbd7b3464e5aa37e9e61d2b01671771c3de3d7e5
package io.xberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnsupportedFormatException with the given message. */
  public UnsupportedFormatException(final String message) {
    super(message);
  }

  /** Creates a new UnsupportedFormatException with the given message and cause. */
  public UnsupportedFormatException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
