// DO NOT EDIT - auto-generated by alef
// alef:hash:9a8216ae03feaf5796cf1b1aca8f859e4332cea6c017ce4aeaef8d22b90274ec
package io.xberg;

/**
 * Invalid configuration or input parameters were supplied.
 */
public class ValidationException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ValidationException with the given message. */
  public ValidationException(final String message) {
    super(message);
  }

  /** Creates a new ValidationException with the given message and cause. */
  public ValidationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
