// DO NOT EDIT - auto-generated by alef
// alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
package io.xberg;

/**
 * Invalid configuration or input parameters were supplied.
 */
public class ValidationException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ValidationException with the given message. */
  public ValidationException(final String message) { super(message); }

  /** Creates a new ValidationException with the given message and cause. */
  public ValidationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
