// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Whitespace handling strategy during conversion.
 *
 * Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
 */
@SuppressWarnings("PMD")
public enum WhitespaceMode {
    /**
     * Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior.
     */
    Normalized("normalized"),
    /**
     * Preserve all whitespace exactly as it appears in the HTML.
     */
    Strict("strict");


    /** The string value. */
    private final String value;

    WhitespaceMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static WhitespaceMode fromValue(final String value) {
        for (WhitespaceMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown WhitespaceMode value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
