// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:df2aaa7155787f2021f495a0a3d7e4be22f8b3be0aecdde41f93e0ae27f5b351
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Whitespace handling strategy during conversion.
 *
 * Determines how sequences of whitespace characters (spaces, tabs, newlines)
 * are processed.
 */
@SuppressWarnings("PMD")
public enum WhitespaceMode {
  /**
   * Collapse multiple whitespace characters to single spaces. Default. Matches
   * browser behavior.
   */
  Normalized("normalized"),
  /**
   * Preserve all whitespace exactly as it appears in the HTML.
   */
  Strict("strict");

  /** The string value. */
  private final String value;

  WhitespaceMode(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static WhitespaceMode fromValue(final String value) {
    for (WhitespaceMode e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown WhitespaceMode value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
