// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:726e46ff2c6bdebea078521e28231803044baac61539acd07d80538d963d6036
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/** Exception thrown by XbergRs. */
public class XbergRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new XbergRsException. */
  public XbergRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new XbergRsException with a cause. */
  public XbergRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() { return code; }
}
