# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d2bedf8545dad2f215a7bbdfc6efcf5454afb74d41a87408dcb6bab2ca049c66
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'extract' do

  it 'extract_bytes_input: extract bytes input from PDF document' do
    result = Xberg.extract(Xberg::ExtractInput.new(bytes: File.binread('pdf/fake_memo.pdf').bytes, filename: 'fake_memo.pdf', kind: 'bytes', mime_type: 'application/pdf'))
    expect(result.results[0].mime_type.to_s).to eq('application/pdf')
    expect(result.results[0].content.length).to be >= 50

  end


  it 'extract_bytes_input_empty_mime: extract bytes input with empty MIME type' do
    expect {
      Xberg.extract(Xberg::ExtractInput.new(bytes: File.binread('text/plain.txt').bytes, config: {  }, filename: 'plain.txt', kind: 'bytes', mime_type: ''), Xberg::ExtractionConfig.new())
    }.to raise_error(RuntimeError)
  end


  it 'extract_bytes_input_invalid_mime: extract bytes input with unsupported MIME type' do
    expect {
      Xberg.extract(Xberg::ExtractInput.new(bytes: File.binread('text/plain.txt').bytes, config: {  }, filename: 'plain.txt', kind: 'bytes', mime_type: 'application/x-nonexistent'), Xberg::ExtractionConfig.new())
    }.to raise_error(RuntimeError)
  end

end
