# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:67e068ab56495acb71bbb36b97e5d1caa1756b12b05aed54a64236363f403c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'post_processor_management' do
  it 'post_processors_clear: Clear all post-processors and verify list is empty' do
    Xberg.clear_post_processors()

  end

  it 'post_processors_list: List all registered post-processors' do
    result = Xberg.list_post_processors()

    expect(result).not_to be_nil
  end
end
