# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ecd62fe5cf2cd8f8328ae99258ebd5e49253419ec89fd33fd9904d4205307faa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'renderer_management' do
  it 'renderers_clear: Clear all renderers and verify list is empty' do
    Xberg.clear_renderers()

  end

  it 'renderers_list: List all registered renderers' do
    result = Xberg.list_renderers()

    expect(result).not_to be_nil
  end
end
