# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a856dbcfccedd609637bcbc8cc8931fee29a18bc3e03bba4d9dada08ea35f8dd
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'tokenizer_backend_management' do

  it 'tokenizer_backends_clear: Clear all tokenizer backends and verify list is empty' do
    expect { Xberg.clear_tokenizer_backends() }.not_to raise_error

  end


  it 'tokenizer_backends_list: List all registered tokenizer backends' do
    result = Xberg.list_tokenizer_backends()

    expect(result).not_to be_nil
  end

end
