# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56b745eaea91253b1a612f56c96ff1541aa7ee2a26fd91afe7d4ec84ab880cff
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'validator_management' do

  it 'validators_clear: Clear all validators and verify list is empty' do
    expect { Xberg.clear_validators() }.not_to raise_error

  end


  it 'validators_list: List all registered validators' do
    result = Xberg.list_validators()

    expect(result).not_to be_nil
  end

end
