# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91f342e9ff393fd2603ce3a50c4348fc049d514675fd2ca14abcf9d8c471c8a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'validator_management' do
  it 'validators_clear: Clear all validators and verify list is empty' do
    Xberg.clear_validators()

  end

  it 'validators_list: List all registered validators' do
    result = Xberg.list_validators()

    expect(result).not_to be_nil
  end
end
