# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.0.12"
end
