# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0e1c5c15465f2c9da4f2fcf714b1b89f3893986d5fd4cea462737f5f31d0c1e3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.0.5"
end
