<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5d2cc8109b1b83b247fcd8370b73cebbf9c792eda9140c054eb5e2a8566105d5
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace Xberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    /**
     * Create a fresh counter with no previous state.
     */
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
