// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:67e068ab56495acb71bbb36b97e5d1caa1756b12b05aed54a64236363f403c3f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: embedding_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_EmbeddingBackendsClear(t *testing.T) {
	// Clear all embedding backends and verify list is empty
	_ = xberg.ClearEmbeddingBackends()
}

func Test_EmbeddingBackendsList(t *testing.T) {
	// List all registered embedding backends
	_, err := xberg.ListEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
