// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c257c1321506b1f3029e4c1b7754280155b10cfedcc0e622fa1200617b818a00
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: post_processor_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_PostProcessorsClear(t *testing.T) {
	// Clear all post-processors and verify list is empty
	_ = xberg.ClearPostProcessors()
}

func Test_PostProcessorsList(t *testing.T) {
	// List all registered post-processors
	_, err := xberg.ListPostProcessors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
