// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:883d7f5978a3ff8d024aea84a120548d00f78251446a657186ecbea5bb27c108
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: post_processor_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_PostProcessorsClear(t *testing.T) {
	// Clear all post-processors and verify list is empty
	result := xberg.ClearPostProcessors()
	if result == nil {
		t.Fatalf("expected non-nil result")
	}
}

func Test_PostProcessorsList(t *testing.T) {
	// List all registered post-processors
	_, err := xberg.ListPostProcessors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
