// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3d8e26ad147a5708354641aac6a7dd10b47730b45c97ccd65b0c84d64a222d6e
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: renderer_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_RenderersClear(t *testing.T) {
	// Clear all renderers and verify list is empty
	result := xberg.ClearRenderers()
	if result == nil {
		t.Fatalf("expected non-nil result")
	}
}

func Test_RenderersList(t *testing.T) {
	// List all registered renderers
	_, err := xberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
