// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: reranker_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_ClearRerankerBackends(t *testing.T) {
	// Clear all reranker backends and verify list is empty
	_ = xberg.ClearRerankerBackends()
}

func Test_ListRerankerBackends(t *testing.T) {
	// List all registered reranker backends
	_, err := xberg.ListRerankerBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
