// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea1f19cde4db09a5faa3c3cfb574fcfeb44db733cdcdf4f32809ff51c0facb61
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: tokenizer_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_TokenizerBackendsClear(t *testing.T) {
	// Clear all tokenizer backends and verify list is empty
	_ = xberg.ClearTokenizerBackends()
}

func Test_TokenizerBackendsList(t *testing.T) {
	// List all registered tokenizer backends
	_, err := xberg.ListTokenizerBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
