// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:52c5c350933264f85bec3c0ed95eda4e4db6d1ae7d77a55f29eb4f17381d0218
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: tokenizer_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_TokenizerBackendsClear(t *testing.T) {
	// Clear all tokenizer backends and verify list is empty
	_ = xberg.ClearTokenizerBackends()
}

func Test_TokenizerBackendsList(t *testing.T) {
	// List all registered tokenizer backends
	_, err := xberg.ListTokenizerBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
